### ISSUE TITLE
model-options

### ISSUE THREAD

**Issue by tph-thuering** [SwissTPH/openmalaria#100]
The following model options should be moved, since they do not dictate fitting parameters:

NON_MALARIA_FEVERS (together with non-malaria fever data)
INCLUDES_PK_PD (now obsolete)
GARKI_DENSITY_BIAS (now obsolete)
REPORT_ONLY_AT_RISK (I think?)
VECTOR_LIFE_CYCLE_MODEL
VECTOR_SIMPLE_MPD_MODEL
PROPHYLACTIC_DRUG_ACTION_MODEL (now obsolete)

All infection model options _could_ be moved to XSD elements under the model element.
In fact, all model options _could_ be moved.

**Comment by ThomasASmith** [comment]
Not a good idea to move things as this would break the existing xml.
