### ISSUE TITLE
remove the "continuous" monitoring code (redundant)

### ISSUE THREAD

**Issue by tph-thuering** [SwissTPH/openmalaria#102]
Notes from @dhardy:

As I understand it, the continuous monitoring system is mostly useful:
a) to quickly get a rough idea of what's going on in a simulation (but better plotting tools like util/plotResults.py maybe make this less important)
b) because using the same "survey times" for all measures is inappropriate

In theory, allowing different measures to use different survey times (perhaps outputting to different files) should get around the issue.

Goal: remove the "continuous" monitoring code since it is redundant and results in quite a bit of extra mess in the code using it.

**Comment by dhardy** [comment]
I'm not sure whether users would agree to this. It's just a possible way to simplify code.

**Comment by ThomasASmith** [comment]
Still unclear if this is a good idea: it would either break some xml or simply mean that some outputs went missing.  I suggest this should wait until/unless there is a major code rewrite.
