### ISSUE TITLE
cmake optimisation: use inline GSL functions

### ISSUE THREAD

**Issue by tph-thuering** [SwissTPH/openmalaria#105]
Could potentially optimise a bit by using inline GSL functions

GSL inline defs:
https://www.gnu.org/software/gsl/manual/html_node/Inline-functions.html#Inline-functions
also:
https://www.gnu.org/software/gsl/manual/html_node/Compatibility-with-C_002b_002b.html#Compatibility-with-C_002b_002b

**Comment by dhardy** [comment]
Documentation moved: https://www.gnu.org/software/gsl/doc/html/usage.html#inline-functions

**Comment by dhardy** [comment]
Quick testing does not show significant differences in performance with or without this macro definition.
