### ISSUE TITLE
analyse-heterogeneities

### ISSUE THREAD

**Issue by tph-thuering** [SwissTPH/openmalaria#107]
Recently added ITN implementation only uses covariance of heterogeneous
parameters, while the sampling of mosquito/human interaction parameters has no
covariance.

In theory we should probably implement both, and perhaps use them as different
submodels (or just check which is the most important).

**Comment by dhardy** [comment]
This is about model variations: how to sample random variables in the ITN model.

**Comment by ThomasASmith** [comment]
Also related to #195
