### ISSUE TITLE
non-const-pop-size

### ISSUE THREAD

**Issue by tph-thuering** [SwissTPH/openmalaria#110]
Use of Population::_populationSize needs to be checked in code for this.

> Diggory
> 
> So far rho has always been zero.   Ideally we would like it to be able
> to take small positive values (population growth) but this is not a
> priority.
> I think this should be flagged as a rather distant TODO with the text of
> your mail somewhere in the documentation of the TODO
> 
> Tom
> 
> Diggory Hardy wrote:
> 
> > Hi,
> > 
> > One little thing I noticed (in update1):
> > {{{#!cpp
> > 
> >   //targetPop is the population size at time t allowing population growth
> >   int targetPop = (int)(_populationSize *
> >   exp(rho*Simulation::simulationTime));
> > 
> > }}}
> > 
> > Is rho ever non-zero? (It defaults to zero if not present.) Currently
> > some of the code (largely vector code I've written, but also
> > checkpointing), uses _populationSize as the current, exact, population
> > size; hence there will be problems (checkpoints should crash, vector
> > calculations off) if rho is non-zero.
> > 
> > So should I correct this? (Currently I just put a catch in to check rho
> > is zero. It doesn't really make sense to have code like this which never
> > does anything, of course.)
> > 
> > Another thing with _populationSize is that it's used to find per-human
> > averages (at least in the vector code), however the number of
> > individuals who's params are added up is going to be less than popSize,
> > due to some being out-migrated or dying of old age, and new births not
> > getting added until after the loop. Actually, too-old individuals die
> > immediately while outmigrated indivs aren't removed until after being
> > updated in the loop which doesn't make much sense... I'm a bit wary of
> > the knock on effects of changing the whole ordering though.
> > 
> > DH

**Comment by dhardy** [comment]
@ThomasASmith This note has been around a long time. Are you saying I should look into implementing non-const population sizes now? I can't guess how difficult this is without looking further into it.

**Comment by ThomasASmith** [comment]
No its not urgent.  I was just tidying up which issues are assigned to whom.

On 19.08.2015 20:43, Diggory Hardy wrote:
>
> @ThomasASmith <https://github.com/ThomasASmith> This note has been 
> around a long time. Are you saying I should look into implementing 
> non-const population sizes now? I can't guess how difficult this is 
> without looking further into it.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/SwissTPH/openmalaria/issues/110#issuecomment-132737930>.
>


-- 
Thomas Smith
Swiss Tropical & Public Health Institute
Department of Epidemiology & Public Health
Socinstrasse 57
P.O . Box
CH-4002 Basel
Switzerland
Tel  +41 61 284 8273 Fax +41 61 284 8101
email: Thomas-A.Smith@unibas.ch
http://www.swisstph.ch/about-us/departments/epidemiology-and-public-health-eph/health-systems-research-and-dynamical-modelling.html
