### ISSUE TITLE
Bug when compiling on Windows: binary '==': no operator found ..  of type 'std:ostream'

### ISSUE THREAD

**Issue by tph-thuering** [SwissTPH/openmalaria#111]
```
C:\projects\openmalaria\model\Simulator.cpp(445): error C2678: binary '==' : no operator found which takes a left-hand operand of type 'std::ostream' (or there is no acceptable conversion) [C:\projects\openmalaria\build-win\model\model.vcxproj]
```
See here: https://ci.appveyor.com/project/tph-thuering/openmalaria/build/windows_appveyor-build_27#L447

It seems to me, that the Microsoft Foundation Classes lack this operator for streams.

The comparison [here](https://github.com/SwissTPH/openmalaria/blob/master/model/Simulator.cpp#L445) causes this error.

in `void Simulator::checkpoint (ostream& stream, int checkpointNum)`
```
    util::checkpoint::header (stream);
    if (stream == NULL || !stream.good())
        throw util::checkpoint_error ("Unable to write to file");
```

possible Solution
------
@dhardy : should I change the second line to

```
    if (!stream.good())
```
?

It seems to me, that stream.good() should be enough to determine if the stream has access to the file.
I'm asking because this has been there since at least 2011 and I don't think MSVC accepted it like this before. I'm guessing people just patched it by hand when trying to compile on Windows.

**Comment by dhardy** [comment]
`stream == NULL` looks like a null pointer check. But `stream` is a reference, not a pointer, so cannot be null. Looks like a relic to me; just remove the check like you suggested.

**Comment by tph-thuering** [comment]
Done: https://github.com/SwissTPH/openmalaria/commit/256446930bee374dd840623b0646c2efaa1b3269
