### ISSUE TITLE
Add tests for GVI-usage + IRS-usage

### ISSUE THREAD

**Issue by tph-thuering** [SwissTPH/openmalaria#113]
As #56 is now implemented, write tests for it.

**Comment by tph-thuering** [comment]
* Implement changes in scenario converter 33_to_34
* make usage an optional parameter.

The following tests are failing currently and need updates:
	 10 - 2ITNs (Failed)
	 15 - IRS30 (Failed)
	 23 - Rach5IC (Failed)
	 26 - VecFullTest (Failed)

**Comment by tph-thuering** [comment]
Tests are not necessary to be changed, as they are optional now. see 4ddba287b2f1d079b9bae7514a828ce8381421fe

**Comment by dhardy** [comment]
I thought the *add tests* title was more about testing the new functionality than fixing compatibility issues?

**Comment by tph-thuering** [comment]
@dhardy You think they are needed? At first I did make them mandatory, but changed it to optional (in XSD-context: minOccurs=0), so existing tests don't need to be changed. So I think tests would be obsolete in this case (I even chose this title).

Do you think I should create additional tests specifically for GVI- and IRS-usage?

**Comment by dhardy** [comment]
Making them optional is a good idea; it'll save a bunch of complaints about *my XML is broken*!

In theory there should be tests for every feature, but to do this properly you need (a) to do a mini-experiment (probably at least pop 10000 and a few repetitions) to check the feature seems to *behave* in the right way, and (b) including the feature in some test scenario with a small pop size (new or existing) to test the feature doesn't get broken by future code changes. But for simple features I'm often lazy; it can be a lot of work.

**Comment by tph-thuering** [comment]
I know there are a few test experiments which have `<usage>0.8</usage>` for ITN. I trust this behaves correct already and IRS + GVI-usage elements behave the same as the code looks the same and scaling of intervention effects is at the same code location for IRS + GVI.
