### ISSUE TITLE
Update information about <monitoring> attribute 'cohortOnly'

### ISSUE THREAD

**Issue by tph-thuering** [SwissTPH/openmalaria#115]
cohortOnly is not used anymore in schema 32, but still the wiki gives examples for it.

Please look through all occasions where cohortOnly is specified and update the documentation.

The following pages contain the search term 'cohortOnly'

Monitoring.md
SubPopulations.md

**Comment by tph-thuering** [comment]
See also: https://github.com/SwissTPH/openmalaria/blob/master/doc/changelog.txt#L97

**Comment by ThomasASmith** [comment]
The current Information on the wiki correctly refers to the v32 changes, but there is a stub for the material on monitoring of subpopulations.  We need to work out how this is output and  explain this in the wiki.  In comparison to other wiki deficiencies this is a minor one.

**Comment by obriet** [comment]
The current wiki states that V32 has the cohortOnly element in the monitoring element. This, however, is incorrect, and when added, crashes the run.

**Comment by ThomasASmith** [comment]
Olivier

I just corrected this, unless this statement is in two different places.
If it is still there, please correct it.

Tom

On 18.06.2015 20:40, obriet wrote:
>
> The current wiki states that V32 has the cohortOnly element in the 
> monitoring element. This, however, is incorrect, and when added, 
> crashes the run.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/SwissTPH/openmalaria/issues/115#issuecomment-113253527>.
>


-- 
Thomas Smith
Swiss Tropical & Public Health Institute
Department of Epidemiology & Public Health
Socinstrasse 57
P.O . Box
CH-4002 Basel
Switzerland
Tel  +41 61 284 8273 Fax +41 61 284 8101
email: Thomas-A.Smith@unibas.ch
http://www.swisstph.ch/about-us/departments/epidemiology-and-public-health-eph/health-systems-research-and-dynamical-modelling.html
