### ISSUE TITLE
Possible bug         <subPopRemoval onFirstBout="true"/>

### ISSUE THREAD

**Issue by ThomasASmith** [SwissTPH/openmalaria#117]
The key lines of Ewan Cameron's code: with these commands people never get taken
out of the "never symptomatic" cohort, even though they should after
their first bout! (the EIR is high and I know that clinical illness
bouts are occurring!)

```
<interventions name="vector pop tests">
   <human>
       <component id="never symptomatic">
         <recruitmentOnly/>
         <subPopRemoval onFirstBout="true"/>
       </component>
       <deployment>
       <component id="never symptomatic"/>
         <continuous>
         <deploy targetAgeYrs="0.01" coverage="1.0"/>
         </continuous>
      </deployment>
   </human>
</interventions>
```

**Comment by ThomasASmith** [comment]
<interventions name="vector pop tests">
   <human>
       <component id="never symptomatic">
         <recruitmentOnly/>
         <subPopRemoval onFirstBout="true"/>
       </component>
       <deployment>
       <component id="never symptomatic"/>
         <continuous>
         <deploy targetAgeYrs="0.01" coverage="1.0"/>
         </continuous>
      </deployment>
   </human>
</interventions>

**Comment by tph-thuering** [comment]
FYI: seems to me, that this is where the removal should happen: https://github.com/SwissTPH/openmalaria/blob/master/model/interventions/InterventionManager.cpp#L107

**Comment by ThomasASmith** [comment]
Dear Tobias,

It seems to me that the line you referenced refers to where the code is 
reading the xml to store the information that removals should take place.

The line where the human should be removed is:

https://github.com/SwissTPH/openmalaria/blob/f4339123acb90ee47608cce70576081df081f876/model/Clinical/CM5DayCommon.cpp#L89

Would you know how to run a debugger to check whether this line of code 
is ever reached within Ewan's simulation?

Best
Tom

On 09.07.2015 15:46, Tobias Thüring wrote:
>
> FYI: seems to me, that this is where the removal should happen: 
> https://github.com/SwissTPH/openmalaria/blob/master/model/interventions/InterventionManager.cpp#L107
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/SwissTPH/openmalaria/issues/117#issuecomment-119974137>.
>


-- 
Thomas Smith
Swiss Tropical & Public Health Institute
Department of Epidemiology & Public Health
Socinstrasse 57
P.O . Box
CH-4002 Basel
Switzerland
Tel  +41 61 284 8273 Fax +41 61 284 8101
email: Thomas-A.Smith@unibas.ch
http://www.swisstph.ch/about-us/departments/epidemiology-and-public-health-eph/health-systems-research-and-dynamical-modelling.html

**Comment by tph-thuering** [comment]
Do you too get this warning when running your scenario?

```
Deprecation warning: healthSystem: use of ImmediateOutcomes can be replaced by the more flexible DecisionTree5Day (optional)
```

This will most probably not reach CM5DayCommon.cpp and thus not remove the people from the cohort on first bout..

I assume changing

```
<healthSystem>
  <ImmediateOutcomes ..>
  ...
  </ImmediateOutcomes>
</healthSystem>
```
to
```
<healthSystem>
  <DecisionTree5Day ..>
  ...
  </DecisionTree5Day>
</healthSystem>
```
might fix the issue here.

**Comment by tph-thuering** [comment]
@ThomasASmith Nevermind, I used the wrong build setting... Using a Debug build the code is reached.

**Comment by tph-thuering** [comment]
I think I know why removal does not happen:

at https://github.com/SwissTPH/openmalaria/blob/master/model/Host/Human.cpp#L184
```
void Human::removeFirstEvent( interventions::SubPopRemove::RemoveAtCode code ){
    const vector<ComponentId>& removeAtList = interventions::removeAtIds[code];
    for( vector<ComponentId>::const_iterator it = removeAtList.begin(), end = removeAtList.end(); it != end; ++it ){
...
```

`removeAtList` is always empty, even though onFirstBout is specified in the XML and the subpopulation identifier is pushed to the `removeAtIds` List.

here: https://github.com/SwissTPH/openmalaria/blob/master/model/interventions/InterventionManager.cpp#L108
```
                if( removeOpts.getOnFirstBout() ){
                    removeAtIds[SubPopRemove::ON_FIRST_BOUT].push_back( id );
                }
```

I fail to understand why this happens..

@dhardy could you help me with this?

you could use this patch and use the scenario from here for testing:
https://gist.github.com/tph-thuering/6950ca1b79e968fe3139

**Comment by dhardy** [comment]
Is it because of the following?

                const scnXml::SubPopRemoval& removeOpts = component.getSubPopRemoval().get();
                if( removeOpts.getOnFirstBout() ){
                    removeAtIds[SubPopRemove::ON_FIRST_BOUT].push_back( id );
                }
                if( removeOpts.getOnFirstTreatment() ){
                    removeAtIds[SubPopRemove::ON_FIRST_INFECTION].push_back( id );
                }
                if( removeOpts.getOnFirstTreatment() ){
                    removeAtIds[SubPopRemove::ON_FIRST_TREATMENT].push_back( id );
                }

`getOnFirstTreatment()` turns both `ON_FIRST_INFECTION` and `ON_FIRST_TREATMENT` on, while `getOnFirstInfection()` is never accessed. But, since this scenario turns all three *on-first-xxx* options on, they should all be turned on in the model.

**Comment by tph-thuering** [comment]
@dhardy No. But I think you found another bug :+1: 

The issue is that `removeAtIds` is empty after `InterventionManager::init()` is done.
It is filled with data however but we're not able to access it from outside.

I would expect that since `removeAtIds` is static, it would be available after InterventionManager was initialized, but that does not seem to be the case.

**Comment by dhardy** [comment]
I think @tph-thuering hit the nail on the head with his questions about `static` vs `extern`. Within a class, C++'s `static` means about the same as `C`'s `static` but outside a class `extern` means about the same and `static`... possibly does nothing. What a confusing language C++ is.

Anyway, I think this should fix it.

**Comment by dhardy** [comment]
Ah no, `static` variables at the namespace scope are [restricted to the translation unit](http://stackoverflow.com/a/15235626/314345). Obscure feature, and orthogonal to other uses of the keyword...

**Comment by tph-thuering** [comment]
I can confirm this bug is fixed :+1:  @dhardy Thank you!

**Comment by tph-thuering** [comment]
Bugfix build released: https://github.com/SwissTPH/openmalaria/releases/tag/schema-33.0.1
