### ISSUE TITLE
Update Vivax model

### ISSUE THREAD

**Issue by tph-thuering** [SwissTPH/openmalaria#126]
Implement for vivax a second release, which allows liver-stage to blood-stage transition of vivax after winter.

**Comment by tph-thuering** [comment]
Track progress here: https://github.com/SwissTPH/openmalaria/tree/vivax-bloodstage-update

**Comment by tph-thuering** [comment]
Changes in test output from old model to new (using no hypnozoite relapse): https://gist.github.com/tph-thuering/0ab7b68af099240da4ec

**Comment by dhardy** [comment]
@tph-thuering the pop-size is 100 so looking at changes in output is not very meaningful (except in situations where only one or two measures change).

You could re-run on both model versions with 5000 or so humans, then use `plotResult -a -f line out1.txt out2.txt` to compare.

**Comment by tph-thuering** [comment]
@dhardy Thank you for the info, this might come in handy later, when verifying if it all works like we expect.

I have another issue though:

I use random::bernoulli() for calculating to which probability distribution a relapse belongs, but then I get different results each scenario run.

How can I keep the random generator in the same state? (using the same seed I presume, but I'm not sure if OM::util::random::bernoulli() does that).

**Comment by tph-thuering** [comment]
@dhardy: See here: https://travis-ci.org/SwissTPH/openmalaria/builds/72478696#L455

I output.txt to test/expected/outputVivax.txt and I always get different numbers.

**Comment by dhardy** [comment]
All the random number calls use the set seed. If you are getting different results, some other random numbers are getting pulled in between.

See random.cpp for details.

**Comment by tph-thuering** [comment]
dhardy: 584e and 09c4 fixed that error, thank you!

**Comment by tph-thuering** [comment]
Linux release is out: https://github.com/SwissTPH/openmalaria/releases/tag/vivax-update-briet-1

and build works: https://travis-ci.org/SwissTPH/openmalaria/builds/72492664

@tph-thuering: TODO: Merge into `develop` when Model is verified.

**Comment by tph-thuering** [comment]
@tph-thuering: TODO: Update changelog: https://github.com/SwissTPH/openmalaria/wiki/Changelog#vivax

**Comment by tph-thuering** [comment]
Changes merged: Rest of TODO here: #132
