### ISSUE TITLE
Update documentation after schema-34 release and add tests for new features

### ISSUE THREAD

**Issue by tph-thuering** [SwissTPH/openmalaria#132]
* [x] https://github.com/SwissTPH/openmalaria/wiki/XmlMonitoring#treatments
* [x] Update changelog: https://github.com/SwissTPH/openmalaria/wiki/Changelog#vivax
* [x] Update test scenario or unittest for vivax-updates:
  * [x] Test "ignoreCannotReceive" maybe? https://github.com/SwissTPH/openmalaria/commit/bf72e8a5efde9d9252465e3d89c6b2ea85a56dcd
* [x] Add note about new `--print-genotypes` argument: https://github.com/SwissTPH/openmalaria/issues/136#issuecomment-134544042 [Documentation](https://github.com/SwissTPH/openmalaria/wiki/DrugResistanceGenotypes#monitoring-of-the-dynamics-of-drug-resistance)

@dhardy: Please add some more locations which need updates here by commenting or adding to this Issue post

**Comment by dhardy** [comment]
I think you've got most of it. Yes, ideally there should be a test scenario or unit test for this.

Possibly there should be some more general "Vivax" documentation on the Wiki; I suspect documentation is mostly Amanda and Olivier's notes plus one or two rough articles on the models at the moment.

**Comment by dhardy** [comment]
Just pushed the extra test to develop. Works as expected.
