### ISSUE TITLE
Feature Request: rename <primaquine> section

### ISSUE THREAD

**Issue by dhardy** [SwissTPH/openmalaria#133]
The `<primaquine>` section of `<ImmediateOutcomes>` and `<DecisionTree5D>` element should be renamed since it can be used to model other liver-stage treatments. Comments from Olivier:

          The only comment, perhaps, is to change the name of the primaquine
          section to something more generic like "liverStageDrug" or
          something like that. One new drug in development is
          tafenoquine. "Like primaquine, tafenoquine has potential to
          cause severe adverse reactions in patients with G6PD
          deficiency, so it will be important that new tests are
          developed to screen patients who would need treatment."
          Perhaps Amanda can comment. But for now, this is not urgent.

**Comment by ThomasASmith** [comment]
Providing this doesn't break anything in Schema 34 it looks to me like this should be added as a synonym in Schema 34.  Then it is out of the way.

**Comment by tph-thuering** [comment]
This breaks at least [`test/scenarioVivax.xml`](https://github.com/SwissTPH/openmalaria/blob/develop/test/scenarioVivax.xml#L120).

I don't know yet of a synonyms-mechanism for XML Schema other than defining identical elements with different names and defining it as alternatives.
This can be done, but I'd rather rename it and integrate the needed changes into our [translation-script for upgrades](https://github.com/SwissTPH/openmalaria/wiki/XmlUpdateScenario#from-schema-version-32-on).

**Comment by dhardy** [comment]
@ThomasASmith Not my place to say, but what Tobi says makes sense. Using a "synonym" is going to introduce a fair bit of unwanted complexity.

Besides, as Tobi points out, we have a script to update OM XMLs.

**Comment by ThomasASmith** [comment]
We agreed that this could be changed in v34 (doesn't need to be held 
over to v35 and hence no synonym)

On 19.08.2015 20:37, Diggory Hardy wrote:
>
> @ThomasASmith <https://github.com/ThomasASmith> Not my place to say, 
> but what Tobi says makes sense. Using a "synonym" is going to 
> introduce a fair bit of unwanted complexity.
>
> Besides, as Tobi points out, we have a script to update OM XMLs.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/SwissTPH/openmalaria/issues/133#issuecomment-132735607>.
>


-- 
Thomas Smith
Swiss Tropical & Public Health Institute
Department of Epidemiology & Public Health
Socinstrasse 57
P.O . Box
CH-4002 Basel
Switzerland
Tel  +41 61 284 8273 Fax +41 61 284 8101
email: Thomas-A.Smith@unibas.ch
http://www.swisstph.ch/about-us/departments/epidemiology-and-public-health-eph/health-systems-research-and-dynamical-modelling.html

**Comment by tph-thuering** [comment]
PR #137 has been merged. (which means it is integrated into the development version/develop branch)
