### ISSUE TITLE
Fix metabolite drug factor calculation to match AS and AR conversion model unittests.

### ISSUE THREAD

**Issue by tph-thuering** [SwissTPH/openmalaria#134]
See https://github.com/SwissTPH/openmalaria/blob/develop/model/PkPd/Drug/LSTMDrugConversion.cpp#L114

```
double calculateMetaboliteQuantity(struct Params_convFactor p, double qtyG, double qtyP, double qtyM, double expAbsorb, double expPLoss, double t) {
    return p.g * qtyG * expAbsorb
        + (p.h * qtyG - p.i * qtyP) * expPLoss
        + (p.j * qtyG - p.i * qtyP + qtyM) * exp(p.nkM * t);
}
```
```
double calculateMetaboliteDrugFactor( struct Params_convFactor p, double expAbsorb, double expPLoss, double t ) {
    const double qtyM = calculateMetaboliteQuantity(p, p.qtyG, p.qtyP, p.qtyM, expAbsorb, expPLoss, t);
    const double cM = qtyM * p.invVdM;              // concentrations; mg/l
    const double cnM = pow(cM, p.nM);               // (mg/l) ^ n
    //FIXME:
    // correctional factor tries to fix results for metabolite quantity calculation
    const double correction_factor = 0.990718;
    const double fCM = correction_factor * p.VM * cnM / (cnM + p.KnM);  // unitless
    return fCM;
}
```

**Comment by tph-thuering** [comment]
@KatherineKay For later reference.

**Comment by dhardy** [comment]
Tobi, was this trying to account for differences to Katherine's code? If so it would be useful to be able to reproduce her results.

**Comment by dhardy** [comment]
Issue is being worked on in [this branch](https://github.com/SwissTPH/openmalaria/commits/conv-model).

One issue with incorrect drug concentration has been fixed, but some other errors remain (mostly to do with drug factors).

**Comment by dhardy** [comment]
Most PK/PD tests have been checked, all updated to use plenty of precision. As noted in the last commit, the only significant source of errors is the drug factors in the AS-DHA conversion test.

**Comment by dhardy** [comment]
Drug factor differences have been identified as slight methodological differences, [as documented here](https://github.com/SwissTPH/openmalaria/wiki/ScenarioPharmacology#combining-factors-from-the-conversion-model).

We decided the 5-10% difference (only 10% for survival rates under 1 in 10^9) is not that significant for our usage.
