### ISSUE TITLE
Warn user when Molineux model is used with 5-day timestep parameterization?

### ISSUE THREAD

**Issue by tph-thuering** [SwissTPH/openmalaria#135]
From @pemberto
> I noticed that you are using the Molineaux model, from the line:
`<option name="MOLINEAUX_WITHIN_HOST_MODEL" value="true"/>`
This needs the use of the 1-day internal timestep, so the line: 
`<parameters interval="5" iseed="2359" latentp="3">`
needs to be changed to 
`<parameters interval="1" iseed="2359" latentp="3">`
There is more details here:
https://github.com/SwissTPH/openmalaria/wiki/ModelWithinHost
Unfortunately, this does not throw an error message, and it really should do!

**Comment by ThomasASmith** [comment]
The original intention with the Molineaux model was that we would run this as a 1 day time step model.
but we are currently not using this with intervention deployment or monitoring on 1 day steps

The model is currently running 1 day updates of parasite densities and PKPD values within an overall 5-day timestep model so the 'interval=5' parameter is correct.

I will edit the wiki documentation to make this clear.
Currently we do not have any 'true' 1-day models running.
