### ISSUE TITLE
Document genotype id implementation

### ISSUE THREAD

**Issue by tph-thuering** [SwissTPH/openmalaria#136]
It looks like genotype ids just get assigned in iteration, see:

https://github.com/SwissTPH/openmalaria/blob/develop/model/WithinHost/Genotypes.cpp#L141

And the genotype code for monitoring is assembled here:

https://github.com/SwissTPH/openmalaria/blob/develop/model/mon/mon.cpp#L119

Explain the difference of sampling modes (initial, tracking or dynamic).

**Comment by dhardy** [comment]
Yes indeed, but genotypes don't directly correspond to what's described in the XML.

The XML lists Loci and Alleles at each Locus. The Genotype is a combination of one Allele from each Locus. So the number of Genotypes is the product `n_alleles[loc_1] * n_alleles[loc_2] * ...`.

I think the ideal was to have some interface list all genotypes from the loci and alleles specified, but I never got that far. A `--print-genotypes` option might be enough.

**Comment by ThomasASmith** [comment]
So the numbers assigned to the genotypes in the output, in the example of 2 loci, with 3 and 2 alleles respectively, should be:

Genotype     Locus           Allele 
number

1                  1st locus     1st allele
                    assigned       assigned
2                  1st locus      2nd allele
                    assigned       assigned
3                  1st locus      3rd allele
                    assigned       assigned
4                  2nd locus      1st allele
                    assigned       assigned
5                  2nd locus      2nd allele
                    assigned       assigned

If this is correct, we could document it this way.  Is it correct?

**Comment by dhardy** [comment]
No. For a start, it's 3 * 2 = 6 not 3 + 2 = 5. The problem's like numbering cells in an n-dimensional table. I have no idea what the ordering is either, it is deterministic but I'd have to double-check the algorithm which isn't trivial.

Going with a feed-back option to print out all genotypes seems much more reliable than hoping everyone does their maths right and gets the same numbers...

**Comment by ThomasASmith** [comment]
In that case I think there is some priority in solving this and it would be worthwhile for Diggory to implement his proposal for a feed-back option to print out all genotypes.  Creating analogous functionality for the pharmacological output would also seem to make sense.

**Comment by tph-thuering** [comment]
Pull Request #138 implements this `--print-genotypes` feature

**Comment by tph-thuering** [comment]
Documented here: https://github.com/SwissTPH/openmalaria/wiki/DrugResistanceGenotypes#monitoring-of-the-dynamics-of-drug-resistance
