### ISSUE TITLE
IRS for newborns - no effect on availability

### ISSUE THREAD

**Issue by GoogleCodeExporter** [SwissTPH/openmalaria#14]
```
New-born infants should benefit from parents' IRS (also ITN) interventions.

Can't really model without some concept of houses or parents.
```

Original issue reported on code.google.com by `diggory....@gmail.com` on 27 Apr 2010 at 7:21

**Comment by ThomasASmith** [comment]
Do we need any additional functionality to allow for newborns benefitting from previously distributed interventions? This could be done by randomly sampling intervention status from candidate parents.  It will make a  difference to outputs from some previous simulations.  Currently if we are interested in an intervention for newborns we explicitly simulate continuous distribution to them.
