### ISSUE TITLE
drug deployment "profiles"

### ISSUE THREAD

**Issue by tph-thuering** [SwissTPH/openmalaria#142]
deploy drugs via a "profile"

e.g. dosage schedules
* [ ] full day administration
* [ ] half day administration
* [ ] mixed form

full day administration
-----
Administer a full dose every day. amount of days and dosage must be specified. (mg drug amount/kg body-weight)

half day administration
-----
Administer a twice half a dose every day (start of day and middle of day). amount of days and dosage must be specified. (mg drug amount/kg body-weight)

mixed form
-----
A mix between the full-day and half-day schedules can be specified.
e.g. Cloroquine is administered on 2 days with full-day schedules and has half the dose on the last day.

**Comment by dhardy** [comment]
This can all be done in the XML.
