### ISSUE TITLE
Document neonatal mortality model

### ISSUE THREAD

**Issue by dhardy** [SwissTPH/openmalaria#147]
- [ ] Document the original model on the Wiki
- [ ] Document how to set the diagnostic

@rossaman leaving as low-priority as I don't see a sudden need for this. Just organising here.

**Comment by dhardy** [comment]
Just stumbled on some documentation: https://github.com/SwissTPH/openmalaria/wiki/ModelClinical#neonatal-mortality

**Comment by rossaman** [comment]
Hi, I've done the neonatal mortality documentation (and for severe morbidity and mortality) but leaving open since there is a little bit of documentation need for diagnostic and neonatal mortality

**Comment by dhardy** [comment]
@rossaman care to be more specific on what? There should be quite a bit of doc about diagnostics already, and I think also about mortality _somewhere_.

**Comment by rossaman** [comment]
@dhardy Thanks. The mortality is fine, it's on the "Clinical (illness) models" page, I did that over Summer. Diagnostics now has it's own page (it used to be under Case Management). The thing that I am worried is not clear, is the that the diagnostic for neonatal mortality has to be specified or else the neonatal mortality results could be inconsistent between runs. I'm not quite clear on this myself so was hoping to get back to it.

**Comment by ThomasASmith** [comment]
There is now adequate documentation in the wiki
