### ISSUE TITLE
Create new fitting run to estimate currently fixed parameters of Molineaux model

### ISSUE THREAD

**Issue by ThomasASmith** [SwissTPH/openmalaria#150]
It looks to me that the poor fit of our best 1-day time step runs is because nearly all the infections are cleared in the dry season (imposing an upper limit on average prevalence and multiplicity).  A possible tweak of the model to address this is to re-estimate the remaining Molineaux-model within-host parameters

**Comment by ThomasASmith** [comment]
BOINC: 
Further brute force Molineaux 5-day model fitting:
1.	Pairwise with immunity decay (choose 1 immunity decay parameter)
2.	Fit Molineaux peak /duration parameters (switch pairwise off)
3.	Fit peak/duration parameters and immunity decay parameters.
Diggory will set up fitting runs: use runs 1131-1133 as guide.  High priority.

**Comment by dhardy** [comment]
Runs (old): 131, 132, 133
Runs (new): 1131 - 1133
Base (no decay): 134

Existing runs with no immunity decay: three variants

**Comment by tph-thuering** [comment]
Done

**Comment by dhardy** [comment]
Oh dear, `INNATE_MAX_DENS` was the wrong parameter to enable. Also this was only one of three new runs which were requested.

**Comment by tph-thuering** [comment]
which is the right one?

**Comment by dhardy** [comment]
I think the fitting server is pretty-much gone now?
