### ISSUE TITLE
Create outputs for sums of probabilities for severe disease and death

### ISSUE THREAD

**Issue by ThomasASmith** [SwissTPH/openmalaria#151]
Severe disease and deaths: to obtain rates from small simulations it should be possible to sum the probabilities of events to obtain approximations to the numbers of events with much less stochastic variation.

**Comment by dhardy** [comment]
Maybe also indirect severe episodes.

**Comment by dhardy** [comment]
@ThomasASmith the pathogenesis model only calculates the probability of a severe episode after determining that *some* malaria event occurs. Since a significant probability of a serious event requires high parasite density I suppose we can assume `prSevereEpisode` when a malaria event does not occur?

For one-day HS models we should work out what to do when someone is already sick.

We also have a "comorbidity factor". Should we do something with this?

(Only looking at severe disease so far...)

**Comment by ThomasASmith** [comment]
Following our call, I take it you are working with the following answers:

On 20.01.2016 19:59, Diggory Hardy wrote:
>
> @ThomasASmith <https://github.com/ThomasASmith> the pathogenesis model 
> only calculates the probability of a severe episode after determining 
> that /some/ malaria event occurs. Since a significant probability of a 
> serious event requires high parasite density I suppose we can assume 
> |prSevereEpisode| when a malaria event does not occur?
>
|prSevereEpisode=0 when |a malaria event does not occur
>
> For one-day HS models we should work out what to do when someone is 
> already sick.
>
We are not using this.  We could make the new functionality work only 
with 5-day HS models.
>
> We also have a "comorbidity factor". Should we do something with this?
>
The comorbidity factor should affect |prSevereEpisode so doesn't this 
lead to naturally to an effect on expected numbers of severe episodes 
and deaths?
|
>
> (Only looking at severe disease so far...)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/SwissTPH/openmalaria/issues/151#issuecomment-173325019>.
>


-- 
Thomas Smith
Swiss Tropical & Public Health Institute
Department of Epidemiology & Public Health
Socinstrasse 57
P.O . Box
CH-4002 Basel
Switzerland
Tel  +41 61 284 8273 Fax +41 61 284 8101
email: Thomas-A.Smith@unibas.ch
http://www.swisstph.ch/about-us/departments/epidemiology-and-public-health-eph/health-systems-research-and-dynamical-modelling.html

**Comment by dhardy** [comment]
This is done. Commit f224ad320c277255c9927e7efb542c33bda053fb. No doc yet, aside from at the bottom of [this file](https://github.com/SwissTPH/openmalaria/blob/master/model/mon/OutputMeasures.h).

**Comment by dhardy** [comment]
This is done. Commit f224ad320c277255c9927e7efb542c33bda053fb. No doc yet, aside from at the bottom of [this file](https://github.com/SwissTPH/openmalaria/blob/develop/model/mon/OutputMeasures.h).

**Comment by dhardy** [comment]
[Change log](https://github.com/SwissTPH/openmalaria/wiki/Changelog#expected-deaths--severe-cases). [Measure documentation](https://github.com/SwissTPH/openmalaria/wiki/XmlMonitoring#added-in-schema-35).
