### ISSUE TITLE
Fix generated schema doc pages not rendering

### ISSUE THREAD

**Issue by dhardy** [SwissTPH/openmalaria#158]
Some of [these pages](https://github.com/SwissTPH/openmalaria/wiki/schema-Index) time-out rendering. We should make them shorter.

Option 1: split. Means links have to jump between pages and browser has to load a new page more often.

Option 2: simplify layout to make shorter

Option 3: cut some stuff deemed not very important

**Comment by tph-thuering** [comment]
Alternative solution:

Move to schema docs to https://readthedocs.org/

**Comment by ThomasASmith** [comment]
I would prefer Option 1 from Diggory.  It is better not to proliferate platforms to which we link.

**Comment by dhardy** [comment]
@ThomasASmith it's done finally (at least it seems to work). Interventions stuff is on one page, everything else on another.

https://github.com/SwissTPH/openmalaria/wiki/schema-index
