### ISSUE TITLE
Update snippet library to latest version

### ISSUE THREAD

**Issue by ThomasASmith** [SwissTPH/openmalaria#162]
Standing issue

**Comment by ThomasASmith** [comment]
We discussed steps should be:
- [ ] remove the organisation by version number 
- [ ] add a header indicating the original version number and that forward compatibility is anticipated but not guaranteed
- [ ] create a template with placeholders for snippets 
- [ ] insert tags into snippets so that they can be used to populate the template via a more less automated algorithm.

The second half of this is not a priority unless someone indicates that they need it.

**Comment by dhardy** [comment]
I am updating existing snippets into a slightly different format, hopefully satisfying most of the above.

Headers look like this. The absense of a `max-version` hints at forward compatibility:

    
    
    
    

An extension which would be very useful:

- [ ] Automated testing of every snippet, by combining into a complete scenario

However, who would see the messages when this fails?

**Comment by dhardy** [comment]
#167 covers some loose ends

**Comment by dhardy** [comment]
#168 covers automated testing

Closing since the rest of the ticket is complete
