### ISSUE TITLE
Please update instructions for scicore installation

### ISSUE THREAD

**Issue by mainic00** [SwissTPH/openmalaria#163]
We would like to run schema 36 binaries on scicore. Could you please update the build script, or amend the build instructions?

**Comment by dhardy** [comment]
I have no clue on scicore... Thüring? But I'm happy to help by email/phone if need be.

**Comment by ThomasASmith** [comment]
Close in favour of #164

**Comment by tph-thuering** [comment]
The documentation has been updated in the wiki at [Building-openMalaria-on-SciCORE-(BC2)](https://github.com/SwissTPH/openmalaria/wiki/Building-openMalaria-on-SciCORE-(BC2))
