### ISSUE TITLE
Automated testing of snippets

### ISSUE THREAD

**Issue by dhardy** [SwissTPH/openmalaria#168]
The snippet library includes some tags designed to allow automated or guided substitution to produce whole scenarios.

A testing tool could try to produce complete scenarios and schema-validate or run them in order to automatically test each snippet.

**Comment by ThomasASmith** [comment]
If the snippet testing fails then ideally it should generate a comment on an open issue.  We could then easily change who subscribes to getting the comments.  
Niggi was looking at whether webhooks might provide some way of providing such functionality.
