### ISSUE TITLE
Uploading static content to OpenMalaria

### ISSUE THREAD

**Issue by ThomasASmith** [SwissTPH/openmalaria#175]
I created this issue to enable uploading documentation, in line with the following comment I found at:
http://solutionoptimist.com/2013/12/28/awesome-github-tricks/

"Smart use of Issues makes it super easy to uploaded files that are associated with your repository… and these files not part of its commit/change processes. If you create an Issue within your repository, you can drag-n-drop files to the issue comments to automatically upload and attach static content to your repository."

[ParameterValues-EntomologicalModel.pdf](https://github.com/SwissTPH/openmalaria/files/541418/ParameterValues-EntomologicalModel.pdf)

**Comment by ThomasASmith** [comment]
[NonHumanHostInterventions.pdf](https://github.com/SwissTPH/openmalaria/files/619739/NonHumanHostInterventions.pdf)

**Comment by ManuelaRunge** [comment]
I am suggesting to update the Figure "Figure 1 : Experiment Folder structure"  in Experiment Design to  remove the red curly underlines and to correct the "A1.xml ... A2.xml"  to "A1.txt  A2.txt" (A and B have file extension xml while C has file extension txt). [https://github.com/SwissTPH/openmalaria/wiki/ExperimentDesign](url)

![sweepfolderstructure](https://cloud.githubusercontent.com/assets/8237612/26414297/06124b64-40af-11e7-93e3-9e022b5e0dcc.JPG)

**Comment by obriet** [comment]
It's possible to have xml sweeps and txt sweeps!

**Comment by ManuelaRunge** [comment]
Sorry my mistake - I changed the picture back with xml and txt sweeps!
(But kept the red lines removed).
