### ISSUE TITLE
Installation issues __Schema document 'scenario_current.xsd' has different target namespace

### ISSUE THREAD

**Issue by hellotianjingnew** [SwissTPH/openmalaria#176]
I've followed the install instructions of Easy Installation (Windows) and also Advanced Installation (Windows) to install and run the OpenMalaria Schema-36.1.  I have tried it on Windows 10 64bit and 31bit. When I ran run-example-scenario.bat, I received error like below:

BoincWrapper: not using BOINC
XSD error: instance document parsing failed
:2:248 error: schema document 'scenario_currrent.xsd' has different target namespace from the one specified in instance document 'http://openmalaria.org/schema/scenario_35'
:2:248 error: no declaration found for element 'om:scenario'
:2:248 error: attribute 'name' is not declared for element 'om:scenario'
:2:248 error: attribute 'schemaVersion' is not declared for element 'om:scenario'

I ran openMalaria.exe --Version and it returned:

schema version: 36
program version: schema-36.1

Can anyone please tell me how run scenario.bat successfully? Thanks.

**Comment by rossaman** [comment]
Hi, The download example_scenario.xml is version 35 but the version you are running is version 36. We need to update the download version. In the meantime as a fix you can 
1. open example_scenario.xml in an editor
2. The top 5 lines include '35' three times. Change these to '36'. 
3. Try re-running.
It should work.

**Comment by hellotianjingnew** [comment]
Hi Rossaman,

Thanks. It worked!

Jing
