### ISSUE TITLE
update example_scenario.xml to current version in the easy installation download

### ISSUE THREAD

**Issue by rossaman** [SwissTPH/openmalaria#177]
@tph-thuering We had a case where a user from Asia could not run the easy-installation since the example_scenario.xml was still on version 35. We fixed it temporarily by changing the 35s to 36s at the top of the xml. Could this be part of the workflow for updating versions?

**Comment by ThomasASmith** [comment]
I also tried to do this and it is not yet fixed.  I could get it to work by changing all the references to version 35 to version 36, so it should not be difficult to fix this.

**Comment by rossaman** [comment]
Yes, I added it as an issue for Tobi to update the workflow so it is always up-to-date. 

-----ThomasASmith <notifications@github.com> wrote: -----
To: SwissTPH/openmalaria <openmalaria@noreply.github.com>

**Comment by dhardy** [comment]
You're referring to the `example_scenario.xml` included in the release? That's a perfectly valid fix @rossaman .

I wonder if we should instead point people to the [snippet repo](https://github.com/SwissTPH/openmalaria.snippets) and have some ready-to-run examples in there?

@tph-thuering where's the release-building-documentation?

**Comment by tph-thuering** [comment]
@dhardy: check for example in .travis.yml:

```
before_deploy:
  - mv -v build/schema/scenario_current.xsd .
  - mv -v build/openMalaria* .
  - cp util/example/run-example-scenario.sh util/example/example_scenario.xml .
  - tar cvzf openMalaria-$TRAVIS_OS_NAME.tar.gz openMalaria* scenario_current.xsd test/autoRegressionParameters.csv test/densities.csv travis-build.json run-example-scenario.sh example_scenario.xml
```

For windows builds it's the same procedure.

This means we just have to update `util/example/example_scenario.xml` and build a new bugfix-release.

**Comment by dhardy** [comment]
@tph-thuering go for it.

**Comment by tph-thuering** [comment]
I've update `example_scenario.xml` and added a [test case](https://travis-ci.org/SwissTPH/openmalaria/jobs/179855002#L1031) for travis-ci to run this scenario.

**Comment by tph-thuering** [comment]
A new release `schema-36.1.1` is underway with these changes in this PR: https://github.com/SwissTPH/openmalaria/pull/178
