### ISSUE TITLE
error running run-example-scenario.sh     

### ISSUE THREAD

**Issue by syzer** [SwissTPH/openmalaria#179]
on mac i get:
```
/run-example-scenario.sh                                                           6 s
dyld: Library not loaded: /usr/local/opt/xerces-c/lib/libxerces-c-3.1.dylib
  Referenced from:
```

**Comment by tph-thuering** [comment]
Hi @syzer :rocket: 

It looks like `xerces-c-3.1` is missing.

Does a
`brew install cmake gcc xerces-c cxxtest boost gsl xsd` help?

Please have a look at our installation instructions for openMalaria on OS X and add a comment whether or not this helped resolve this issue.

https://github.com/SwissTPH/openmalaria/wiki/Installation#os-x

**Comment by tph-thuering** [comment]
Since brew provides [3.1.4](https://github.com/Homebrew/homebrew-core/blob/master/Formula/xerces-c.rb#L4), this should be up to date if you run `brew install xerces-c`

**Comment by tph-thuering** [comment]
Since there is no response from @syzer, but I know he fixed it I'll close this issue.
