### ISSUE TITLE
TODO items in code

### ISSUE THREAD

**Issue by GoogleCodeExporter** [SwissTPH/openmalaria#18]
There are many FIXME, BUG, WARNING, TODO or NOTE tags in the code. This is
a permanent issue as a reminder to look for these.

Command:

```
egrep -IR '\b(FIXME|BUG|WARNING|TODO|NOTE|HACK)\b' include/ model/
```

Items not intended to get attention this way should be renamed (e.g. to
lower-case). Significant items could have an issue added here too/instead.

**Comment by dhardy** [comment]
This is an "on-going" task: just a reminder to check for these things occasionally.
