### ISSUE TITLE
scicore build schema 36 needs library to run

### ISSUE THREAD

**Issue by obriet** [SwissTPH/openmalaria#180]
When trying to run the version in "/scicore/home/smith/GROUP/CODE/OpenMalaria/OM_schema36"  on BC2 I get the following error
./openMalaria: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by ./openMalaria)

Cheers,

Olivier

**Comment by dhardy** [comment]
I haven't done any cluster builds for a while and don't think I have access, sorry.

**Comment by obriet** [comment]
I found in a read.me file:
"This build was built with ./build-bc2-release.sh
* from user Tobias Thüring <tobias.thuering@unibas.ch>
* at 2016-07-04
* from branch 'master' and git-tag 'schema-36.1'
* on host 'login14.cluster.bc2.ch' ("CentOS release 6.5 (Final)").
* and published on https://github.com/SwissTPH/openmalaria/releases/tag/schema-36.1

Before running openMalaria make sure to load GCC as a module first with
this command (also load the correct GCC version):
  $ module load GCC
"

I have not tried this yet, but is likely to solve the issue

**Comment by tph-thuering** [comment]
Yes, this solves the issue as documented.

Greetings
