### ISSUE TITLE
P_A in continuous output is wrong

### ISSUE THREAD

**Issue by obriet** [SwissTPH/openmalaria#181]
With very low mosqHumanBloodIndex, continuously monitored P_A = 1-mosqLaidEggsSameDayProportion (As it should be). However, with higher mosqHumanBloodIndex, continuously monitored P_A is about 10% off.

**Comment by ThomasASmith** [comment]
Do we know why?

**Comment by obriet** [comment]
Yes, we have probably found the explanation, see message pasted below.
Olivier

-----Olivier Briet/TPH wrote: -----
To: Amanda Ross/TPH@STI
From: Olivier Briet/TPH
Date: 12/23/2016 04:39PM
Cc: Nakul Chitnis/TPH@STI, Thomas Smith/TPH@STI
Subject: Re: Fw: [SwissTPH/openmalaria] P_A in continuous output is wrong (#181)

Dear Amanda,

I am around today, but then not until 3rd of 4th.
I  discussed with Nakul, and he suggested that, with high probability, the  issue is due to OpenMalaria calculating P_A after adjusting for  age-dependent human availability to mosquitoes towards the end of the  warm up and onward, whereas during initialization,  P_A = 1-mosqLaidEggsSameDayProportion, with each human being equally available (as per definition). With very low mosqHumanBloodIndex, the age structured availability in humans does not affect the estimate. 

Essentially,  P_A in the continuous output is NOT wrong (so you don't have to rerun),  it is just not what-you-put-in-is-what-you-get (similar to the  simulated EIR not being equal to the input EIR, especially for low EIR).

Olivier  


-----ThomasASmith <notifications@github.com> wrote: -----
To: SwissTPH/openmalaria <openmalaria@noreply.github.com>

**Comment by dhardy** [comment]
So @obriet do you want to close this? If not please update the title and explain better.

**Comment by obriet** [comment]
Yes, please go ahead and close.

-----"Diggory Hardy" <notifications@github.com> wrote: -----
To: "SwissTPH/openmalaria" <openmalaria@noreply.github.com>
