### ISSUE TITLE
Remove util/example and hook in Travis?

### ISSUE THREAD

**Issue by dhardy** [SwissTPH/openmalaria#186]
Tobi, I think you added this? Does it add any value over the other examples in the test dir? It seems to be something extra to update every release without much value from my point of view.

**Comment by tph-thuering** [comment]
Yes, this was on request of users wanting to have an example bundled in the release build.

I would advise not to remove it, but rather automate schema-release changes needed.

**Comment by dhardy** [comment]
Okay. #188 is a good idea. I admit, I forgot _again_ to add the new schema file to git (after creating it) so it should also do that.
