### ISSUE TITLE
Human-based interventions having an impact on fertility of mosquitoes

### ISSUE THREAD

**Issue by obriet** [SwissTPH/openmalaria#189]
New combinations long-lasting insecticidal nets are being developed that are treated with a pyrethroid and pyriproxyfen, an insect growth regulator that disrupts the maturation of oocytes in mosquitoes exposed to the net. Resistant mosquitoes don't die but take a blood meal, yet have a reduced number of viable eggs.
We want to model this (assuming that the effect lasts only for the duration of the present gonotrophic cycle) by introducing PFi, the probability of eggs being fertile after biting host i.
Then Pdf.f = Sum(PAi*PBi*PCi*PDi*PEi*PFi) is the Probability of finding a host and surviving the feeding cycle and producing fertile eggs. (Analogous to Pdf= Sum(PAi*PBi*PCi*PDi*PEi)). 

This would have an effect only with the simple dynamic model  option active (described in [  https://github.com/SwissTPH/OpenMalaria/wiki/ModelMosqPopDynamics ] and in [
https://github.com/SwissTPH/openmalaria/wiki/docs/MosquitoLifeCycleSimplePer.pdf
]), where equation 2b y(t) = b*Pdf*x(t-tau); would be modified into y(t) = b*Pdf.f*x(t-tau);.

Such functionality would also allow the modeling of reduced fecundity after biting hosts with less suitable blood (see e.g. : http://scialert.net/fulltext/?doi=je.2011.459.467&org=10).

ITNs (and possibly GVI) intervention parameterizations would incorporate an infertility inducing effect PFmu, for protected humans (PF.mu.h.p) versus unprotected humans (PF.mu.h.u). 
PF.h.p <- PFi.h.u * (1-PFmu.h.p) / (1-PFmu.h.u).
For the  ITNs parameterization, PFmu would be modeled analogous to e.g. the post-prandial killing effect, depending on pyriproxyfen concentration (and possibly, on holes).

**Comment by dhardy** [comment]
Implemented by #198
