### ISSUE TITLE
Fix automated builds

### ISSUE THREAD

**Issue by tph-thuering** [SwissTPH/openmalaria#191]
# Problem:

`$ ./run-example-scenario.sh` does not run without failure.

# Probable Cause:

XSD version reference corresponds to `schema/scenario_current` instead of the release version e.g. `scenario/schema_37`

# Proposed fix:

Generate the proper xml schema definition reference for the example shell script for release builds to be bundled in the example zip for download, so new users can verify their installation with the example script:

Correct
```xml
<xs:schema targetNamespace="http://openmalaria.org/schema/scenario_37" xmlns:om="http://openmalaria.org/schema/scenario_37" xmlns:xs="http://www.w3.org/2001/XMLSchema">
```

False
```xml
<xs:schema targetNamespace="http://openmalaria.org/schema/scenario_current" xmlns:om="http://openmalaria.org/schema/scenario_current" xmlns:xs="http://www.w3.org/2001/XMLSchema">
```

# debug: Log from build pipeline: https://travis-ci.org/SwissTPH/openmalaria/builds/208894653
```bash
$ ./run-example-scenario.sh

BoincWrapper: not using BOINC

XSD error: instance document parsing failed

:0:0 warning: An exception occurred! Type:RuntimeException, Message:Warning: The primary document entity could not be opened. Id=scenario_37.xsd

:2:243 error: Unknown element 'om:scenario'

:2:243 error: Attribute '{http://www.w3.org/2000/xmlns/}om' is not declared for element 'om:scenario'

:2:243 error: Attribute '{http://www.w3.org/2000/xmlns/}xsi' is not declared for element 'om:scenario'
...
```

**Comment by dhardy** [comment]
That sounds right. Only scenarios in the `test` directory should use `scenario_current`; that only exists for development.

**Comment by tph-thuering** [comment]
Proposed fix on compile time:

Change static definition of xsd in [`schema/CMakeLists.txt`](https://github.com/SwissTPH/openmalaria/blob/06accc2db2a83ebcbc6a133a94d737d2e0be0ce6/schema/CMakeLists.txt#L42) with
* read: https://cmake.org/cmake/help/v3.3/command/file.html?highlight=glob
and
* string pattern matching directives: https://cmake.org/cmake/help/v3.3/command/string.html?highlight=regex 

[Here](https://github.com/SwissTPH/openmalaria/blob/06accc2db2a83ebcbc6a133a94d737d2e0be0ce6/schema/CMakeLists.txt#L30)
`30   --namespace-map http://openmalaria.org/schema/scenario_37=scnXml`
and [here](https://github.com/SwissTPH/openmalaria/blob/06accc2db2a83ebcbc6a133a94d737d2e0be0ce6/schema/CMakeLists.txt#L42)
`42   set( INLINED_XSD ${CMAKE_CURRENT_BINARY_DIR}/scenario_current.xsd )`

**Comment by dhardy** [comment]
What is this? I think it's the script generating the development schema, in which case, no, it *should* be `scenario_current.xsd`. Or change it if you prefer... I haven't touched this in a while anyway.

**Comment by tph-thuering** [comment]
> That sounds right. Only scenarios in the test directory should use scenario_current; that only exists for development.

@dhardy This means we need to distinguish development builds and release builds :-) can you remember which CMake Variable defined this?

**Comment by dhardy** [comment]
I never implemented CMake support for release builds. I just did a few manual steps (update version numbers, copy scenario_current to schema/scenario_VER, create a zip copying files from the previous release and updating numbers).

You can automate properly if you like but I don't see much value given that very little OM development has happened recently.

**Comment by tph-thuering** [comment]
@dhardy to be clear trying to explain my mental model about this topic:

* In development, we want to generate a file called `scenario_current.xsd`
* On release builds, we want to generate a file called `scenario_${MAJOR version}.xsd`

Both need to be referenced in the scenario xml files.
Release versions need to have a MAJOR number referenced in the xml.

**Comment by tph-thuering** [comment]
@dhardy I see your point. I don't thing the fix is too much effort.

@ThomasASmith I would estimate about 2-3 hours to fix this issue. Has this any priority at all?
To clarify:
this affects the `run-example-scenario.bat` script for new users testing the bundled `example_scenario.xml` in the [openMalaria-windows.zip](https://github.com/SwissTPH/openmalaria/releases/download/schema-36.1.1/openMalaria-windows.zip) and also Linux / Mac versions.

Running the script currently only works by changing the first line (reference to xml schema definition version) manually from 'scenario_current' to the appropriate release version.

I propose to adjust the current behaviour so builds correctly generate the xml and its reference.
Previously Diggory or I just copied the `scenario_current.xsd` from the build folder to the schema folder e.g. `scenario_37.xsd` and uploaded it to the git repo whenever we released a new version.

**Comment by dhardy** [comment]
> On release builds, we want to generate a file called scenario_${MAJOR version}.xsd

Sorry @tph-thuering, no. In *any* build we should create `${CMAKE_CURRENT_BINARY_DIR}/scenario_current.xsd`. When making a release, we should *copy* this file to `release_dir/scenario_VER.xsd`.

Standard practice until now has been to keep a copy of every release's XSD file at `openmalaria/schema/scenario_VER.xsd` (this is not *usually* adjusted by patch releases). I guess this step doesn't need to be automated.

**Comment by dhardy** [comment]
So @tph-thuering I was looking at how to fix this, but I don't know what script you use to prepare the release zip/tar.gz files?

While CMake *could* output a `scenario_${MAJOR}.xsd` file, you wouldn't be able to run the test scenarios without editing them, so you couldn't do `ctest`. I suppose a way to solve this would be to get rid of `scenario_current` altogether and always use versioned schema files.

BTW I've often used `CMAKE_BUILD_TYPE=RelWithDebInfo` for development because without optimisations running the tests is quite slow, so the "cmake build mode" isn't a good way to distinguish dev builds and release builds.

**Comment by tph-thuering** [comment]
@dhardy 
> While CMake could output a scenario_${MAJOR}.xsd file, you wouldn't be able to run the test scenarios without editing them, so you couldn't do ctest. I suppose a way to solve this would be to get rid of scenario_current altogether and always use versioned schema files.

The change of the xsd file happens after ctest.

This can all be done in .travis-ci.yml and appveyor.yml files in the `before_deploy` part: https://github.com/SwissTPH/openmalaria/blob/master/.travis.yml#L65

**Comment by dhardy** [comment]
This should be fixed for Linux and OSX builds in #217, though we won't really know until the next release is tagged. #217 deliberately requires some action when updating the schema version.

I believe the build pipeline still needs updating for Windows builds. I am awaiting some help from @aurdipas in getting AppVeyor integration working. The script should also be updated to build the release archives in a similar way to on UNIX.

**Comment by dhardy** [comment]
The schema 41 release appears functional on Windows but not on OSX (GSL lib not found).

**Comment by dhardy** [comment]
Closing: #224 and #253 track remaining issues for specific platforms, allowing this high-priority issue to be closed (my understanding is that remaining aspects are lower priority).
