### ISSUE TITLE
Replace random number generator?

### ISSUE THREAD

**Issue by dhardy** [SwissTPH/openmalaria#194]
OpenMalaria uses the Mersenne Twister 19937 random number generator. I am not an expert on the topic but have heard that although the generator is reasonably good it has some "bad states" from which it takes a while to escape and sequences yielded by nearby seeds may take a while to diverge.

The best fast non-cryptographic RNGs I am aware of are [Xoroshiro](http://xoroshiro.di.unimi.it/) and [PCG](http://www.pcg-random.org/). Fast cryptographic generators may also be of interest, e.g. [ISAAC](http://www.burtleburtle.net/bob/rand/isaacafa.html).

**Comment by dhardy** [comment]
On further reading, [O'Neill doesn't seem to like Xoroshiro](http://www.pcg-random.org/posts/other-good-options.html). He has [some interesting blog posts](http://www.pcg-random.org/posts/visualizing-the-heart-of-some-prngs.html).

**Comment by ThomasASmith** [comment]
I've downgraded this as I think the current code is not broken and there seems to be no overwhelming reason for changing the random number generator.  I would want to know what is the potential saving in compute time.

**Comment by dhardy** [comment]
I noticed in one of Theresa's scenarios that the random number generator took about 40% of the compute time; this was because of the extreme use of many intervention components and some "odd" behaviour (check coverage before checking whether component meets other conditions). Probably in other scenarios performance would not be massively affected; I can't actually measure impact without implementing the change however.

**Comment by dhardy** [comment]
This is a sub-set of #204.

**Comment by dhardy** [comment]
This was done (at least partially) in #242.
