### ISSUE TITLE
Improve interaction of multiple human-vector interventions

### ISSUE THREAD

**Issue by dhardy** [SwissTPH/openmalaria#195]
@obriet has an improved model for interaction of multiple interventions (e.g. IRS + Net):

*   use [two-stage deterrency](https://github.com/SwissTPH/openmalaria/issues/109): entering, attacking
*   mosquitoes deterred from entering by any intervention are not further affected
*   mosquitoes who enter but are deterred from attacking may then be affected by other interventions, using that intervention's existing probabilities:
    
    - deterred from attacking by another intervention (if this interaction has not already been accounted for)
    - killed pre-prandial
    - killed post-prandial

@ThomasASmith should we implement like this? Is it okay just to replace old interaction? This is *probably* a couple of days work.

**Comment by obriet** [comment]
I don't think the current way interaction is 'wrong' in all circumstances (except perhaps when propactive is (ab)used,  but that is a different issue), so if it is possible to maintain the old while developing a parallel improved version, that would have my preference.

Olivier


-----"Diggory Hardy" <notifications@github.com> wrote: -----
To: "SwissTPH/openmalaria" <openmalaria@noreply.github.com>
