### ISSUE TITLE
Fix intervention "usage" interaction

### ISSUE THREAD

**Issue by dhardy** [SwissTPH/openmalaria#196]
Some interventions have a [usage parameter](https://github.com/SwissTPH/openmalaria/wiki/schema-37-intervs#elt-usage-2) describing the proportion of the time a host is protected by this intervention (e.g. in a protected house).

Given multiple interventions, the simulator assumes that protection probabilities are independent (i.e. given usages p, q, then sim assumes chance p*q of double protection and (1-p)*(1-q) of no protection). @obriet points out this may not be correct, e.g. veranda protection and a bed net will not be used simultaneously (so chance of no protection should be (1-p-q)).

How can we fix this? It would appear to need some kind of classification of vector interventions. In the mean-time @obriet has some work-arounds.

@ThomasASmith

**Comment by ThomasASmith** [comment]
It is perhaps worth remembering that this can be an issue, but the situations where it arises are very specific and it seems unlikely there is a simple generic solution.

**Comment by ThomasASmith** [comment]
this seems to be a subset of #195
