### ISSUE TITLE
Make reactive case detection easier and faster

### ISSUE THREAD

**Issue by dhardy** [SwissTPH/openmalaria#197]
"Reactive case detection", i.e. coverage dependent on recent prevalence/incidence history, is currently possible in OpenMalaria — a student has an example involving 5000 intervention components each with their own pre-conditions and coverages. This is not easy to work with either for tooling (requires XML generation via a script) or the simulator (evaluating so many components is slow).

All that is needed in this case is a function calculating coverage based on two parameters. How generic a solution do we need?

@ThomasASmith

**Comment by ThomasASmith** [comment]
We cannot predict what kinds of functions we will need so I do not suggest changing the current functionality.  The fact that the xml with 5000 intervention components runs, demonstrates that it is possible to simulate a remarkable range of different intervention specifications with the existing code.
