### ISSUE TITLE
Shouldn't scenario_38.xsd  use namespace http://openmalaria.org/schema/scenario_38?

### ISSUE THREAD

**Issue by slremy** [SwissTPH/openmalaria#200]
Schema have been the bane of my experience so far.. but I think I'm finally starting to get it... :)
I'm seeing the following:
<xs:schema targetNamespace="http://openmalaria.org/schema/scenario_37"

In [scenario_38.xsd](https://github.com/SwissTPH/openmalaria/blob/master/schema/scenario_38.xsd). Please say that's an error...

**Comment by dhardy** [comment]
Yes, sounds like an error. Manually updating the namespace each version is hit-and-miss, sorry!

**Comment by slremy** [comment]
Understood.

**Comment by ThomasASmith** [comment]
Can we close this issue now? Is it sorted?
