### ISSUE TITLE
checkpoint option

### ISSUE THREAD

**Issue by ManuelaRunge** [SwissTPH/openmalaria#201]
Checkpointing is mentioned as an option for OpenMalaria [https://github.com/SwissTPH/openmalaria/wiki/Running-OpenMalaria ](url). I added the `--checkpoint t` as for example in `openMalaria --scenario scenarios//wutest_0.xml  --output outputsCheckpoint//wutest_0_out.txt  --ctsout outputsCheckpoint//wutest_0_cts.txt    --checkpoint=37 `. 
Is that the correct way to start with? I could not find further explanation of how to use it and how to be theoretically be able to update scenarios starting from the checkpoint (e.g. from t=37). 

In brief, is the checkpoint option working and if so are there any examples of how to use it?

**Comment by dhardy** [comment]
In theory it should work, but I don't know why you'd want it (this was only used with BOINC and during tests). I'm also not sure what times you should use; this is measured in simulation time and since typically 90%+ of the simulation is the warmup phase it would normally checkpoint and quite during that phase. But I just tried the `--checkpoint=100` option without any success; not sure why.

**Comment by ManuelaRunge** [comment]
Adding the `--checkpoint=37` or `--checkpoint=100`  option gives just the normal output files and nothing in addition which would indicate anything about a checkpoint.
I thought that option would enable me to run a set of simulation until a certain timestep at which interventions are deployed, and as the intervention plans change, just  to change the interventions from that timestep onwards, without having to simulate the whole history again.
But I understand that it might unnecessarily complicate the workflow and it is easier to re-simulate everything.
Thanks.

**Comment by dhardy** [comment]
That idea might work in theory for some interventions at least — but anything affecting heterogeneity parameters would not work correctly (these are assigned at birth). Not sure why checkpointing is not working at all however.

**Comment by slremy** [comment]
I too am wondering what happened to the checkpoints!

Centos ... Linux 30134f96d826 4.9.87-linuxkit-aufs # 1 SMP Wed Mar 14 15:12:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

OM built from source (https://github.com/SwissTPH/openmalaria.git -b schema-37.0.2)

**Comment by slremy** [comment]
Hi @dhardy, does https://github.com/SwissTPH/openmalaria/blob/master/model/Simulator.cpp#L186 mean that checkpointing is only available with BOINC?

**Comment by dhardy** [comment]
No. [Line 177](https://github.com/SwissTPH/openmalaria/blob/master/model/Simulator.cpp#L177) should get the next checkpoint time passed via `--checkpoint=` option. The `BoincWrapper` stuff should do nothing without BOINC, but the other bit (`testCheckpointTime == sim::now()`) should still work.

I'm not sure why it doesn't. I'm getting a compile error when trying to build now; something to do with Xerces and C++11, though it may be a compiler bug (OpenMalaria should use C++98).

**Comment by slremy** [comment]
If you'd like to try using a container, you can docker pull slremy/worker-openmalaria-schema-37.0.2:55

We're using <pre>gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4)</pre>

in the ```/model/openmalaria```

**Comment by dhardy** [comment]
Oh, I worked out what the problem is: https://bugzilla.redhat.com/show_bug.cgi?id=1595861

**Comment by slremy** [comment]
So it seems that --checkpoint is not honored, but -c is.. and generates a single checkpoint (at 24% for this scenario file, but for another it was 46%)

```
bash-4.2$ openMalaria -s /model/openmalaria/test/scenarioSubPopRemoval.xml 
BoincWrapper: not using BOINC
[ 99%]	sim end
Total/allowed infections: 357873/357873	(0% prevented)
Human updates/total calls: 2512461/2746000	(8.5047% skipped)


bash-4.2$ openMalaria -s /model/openmalaria/test/scenarioSubPopRemoval.xml --checkpoint=1
BoincWrapper: not using BOINC
[ 99%]	sim end
Total/allowed infections: 357873/357873	(0% prevented)
Human updates/total calls: 2512461/2746000	(8.5047% skipped)


bash-4.2$ openMalaria -s /model/openmalaria/test/scenarioSubPopRemoval.xml --checkpoint=100
BoincWrapper: not using BOINC
[ 99%]	sim end
Total/allowed infections: 357873/357873	(0% prevented)
Human updates/total calls: 2512461/2746000	(8.5047% skipped)


bash-4.2$ openMalaria -s /model/openmalaria/test/scenarioSubPopRemoval.xml -c   
BoincWrapper: not using BOINC
[ 24%]	Checkpoint test: checkpoint written; exiting...


bash-4.2$ openMalaria -s /model/openmalaria/test/scenarioSubPopRemoval.xml 
BoincWrapper: not using BOINC
openMalaria: /model/openmalaria/model/util/CommandLine.cpp:325: static void OM::util::CommandLine::staticCheckpoint(std::istream&): Assertion `tOpt == options.to_string()' failed.
Aborted


bash-4.2$ openMalaria -s /model/openmalaria/test/scenarioSubPopRemoval.xml -c
BoincWrapper: not using BOINC
3285t RC
[ 99%]	sim end
Total/allowed infections: 357873/357873	(0% prevented)
Human updates/total calls: 2512461/2746000	(8.5047% skipped)
```
