### ISSUE TITLE
Trapping zero densities in calculations of log density

### ISSUE THREAD

**Issue by ThomasASmith** [SwissTPH/openmalaria#203]
For any specificity < 1, you get –Inf values for outcome measures outputting sumlogDens. This arises because specificity <1 means some patients with zero parasites are diagnosed as patent, therefore log(0) are calculated for these patients . Perhaps, an if-statement catching these instances would be useful in the OM code????.

**Comment by dhardy** [comment]
Relevant code:
```cpp
            specificity = elt.getStochastic().get().getSpecificity();
            if( specificity < 0.0 || specificity > 1.0 ){
                throw util::xml_scenario_error(
                    string("diagnostics/diagnostic(").append(elt.getName())
                    .append("): specificity must be in range [0,1]") );
            }
```

What do you propose to do to fix this? We could only report somlogDens for humans who actually have non-zero density. But the very idea of *specificity* is that there may be false-positives, right?

**Comment by dhardy** [comment]
We could consider this a bug: OpenMalaria should consider this measure unusable when specificity < 1
