### ISSUE TITLE
output genotype_weights as a standard OM output

### ISSUE THREAD

**Issue by ThomasASmith** [SwissTPH/openmalaria#205]
Tracking resistance allele frequencies in OM is complicated by the presence of multiple infections.  However this could be resolved if the parameter “genotype_weights” were to be output (currently this is not available as an output).  “genotype_weights” is calculated within genotypes.cpp as part of the following code:

uint32_t Genotypes::sampleGenotype( vector<double>& genotype_weights ){
    if( GT::current_mode == GT::SAMPLE_FIRST ){
        return 0;       // always the first genotype code
    }else if( GT::current_mode == GT::SAMPLE_INITIAL
            || genotype_weights.size() == 0 )
    {
        double sample = util::random::uniform_01();
        map<double,uint32_t>::const_iterator it = GT::cum_initial_freqs.upper_bound( sample );
        assert( it != GT::cum_initial_freqs.end() );
        return it->second;
    }else{
        assert( GT::current_mode == GT::SAMPLE_TRACKING );
        assert( genotype_weights.size() == N_genotypes );
        double weight_sum = util::vectors::sum( genotype_weights );
        assert( weight_sum > 1e-5 && weight_sum < 1e5 );        // possible loss of precision or other error
        double sample = util::random::uniform_01() * weight_sum;
        double cum = 0.0;
        for( size_t g = 0; g < N_genotypes; ++g ){
            cum += genotype_weights[g];
            if( sample < cum ) return g;
        }
        assert(false);  // above loop should not terminate
        return 0;       // just to be safe
    }
}

**Comment by dhardy** [comment]
Dear Tom,

I believe this is what the `innoculationsPerAgeGroup` measure does. This is "segregated by human age, cohort membership and parasite genotype".

Internally this is tracked as `TransmissionModel::surveyInoculations` and reported under the following code (which doesn't mention genotype, but does include it):
```
    // Total inoculations over survey period per group (age, cohort). Units: inoculations.
    MVF_INOCS,
```
See `TransmissionModel::getEIR` and `TransmissionModel::summarize`.
