### ISSUE TITLE
hrp2 deletions which make the parasites non-detectable on RDT

### ISSUE THREAD

**Issue by ThomasASmith** [SwissTPH/openmalaria#206]
There is a lot of interest in hrp2 deletions which make the parasites non-detectable on RDT and their clinical implications and impact on MSAT, FSAT  etc.

The task would be to re-purpose drug-resistance alleles in OM to investigate this. Keep drug sensitivity (IC50) the same for “resistant” and “sensitive” alleles but make the former non-detectable by RDTs. Hopefully the code changes should be relatively minor. 

The function Diagnostic::isPositive in the WithinHost  namespace passes densities but presumably that is total density in the patient i.e. “dens”. Could we have a new drug “locus” like “CQ” or “PPQ” but called “hsp2_deletion” and withinhost tracking  passes total parasite densities ignoring clones with hsp2 deletions when this drug class is present?

**Comment by dhardy** [comment]
We have several uses of diagnostics:

-   the number of patent infections (for each infection, test against that infection's density; I'm not sure what this models)
-   sum(log(dens)) per patent infection
-   the number of patent hosts (one diagnostic on total density)
-   sum(log(dens)) per patent patient
-   intervention and health system actions after screening (one diagnostic on total density)

I guess we could address this with one of the following, from less to more complicated:

1.  make the density appear as zero for any allele with hrp2 deletion (add a marker [to the allele])
2.  add a multiplier for "apparent density" [to the allele], allowing weighted sums (simple modelling for hrp3 deletion, perhaps)
3.  use separate specification of the [diagnostic] per allele at this loci

The question is, how much complexity do we need here? Better to get it right first time, but also the simpler the better.

[to the allele]: https://github.com/SwissTPH/openmalaria/wiki/schema-39#elt-allele
[diagnostic]: https://github.com/SwissTPH/openmalaria/wiki/schema-39#elt-diagnostic-3

**Comment by ThomasASmith** [comment]
I vote for number 1.

**Comment by dhardy** [comment]
Is that a decision or is more discussion required? I'm happy to go with it...

**Comment by dhardy** [comment]
It occurs to me that density should only be zero for diagnostics using HRP2, so we might end up with something like this:

```xml
  <parasiteGenetics samplingMode="tracking">
    <locus name="hdr2">
      <allele name="natural" initialFrequency="0.9" fitness="1"/>
      <allele name="invisible" initialFrequency="0.1" fitness="1" hrp2_deletion="true"/>
    </locus>
  </parasiteGenetics>
  <diagnostics>
    <diagnostic name="standard" units="Other" mechanism="HRP2">
      <!-- detection limit 40 according to non-Garki method -->
      <deterministic minDensity="40"/>
    </diagnostic>
  </diagnostics>
```
with the significant bits being
- `mechanism="..."` supporting `HRP2` and `Other`
- `hrp2_deletion="true"` (or `false`)

**Comment by dhardy** [comment]
This is a feature which has some unexpected complexity, namely because we have output summaries not just for patent hosts, but for patent infections and hosts patent with a specific genotype — i.e. we use diagnostics in three different ways:

- is the host patent?
- is a specific infection patent (isolated from other possible infections)?
- is the sum of densities of infections with a specific genotype patent?

Summary: it's a bit more complicated than expected. Using unrealistic summary statistics can cause unexpected issues.

**Comment by ThomasASmith** [comment]
As discussed, the simplest way forward would seem to be to implement this for treatment diagnostics only. (the Wiki will need to explain that it does not do anything to survey diagnostics)
