### ISSUE TITLE
url link broken

### ISSUE THREAD

**Issue by ggrrll** [SwissTPH/openmalaria#209]
Hi,

the link to TPH team in this [wiki page](https://github.com/SwissTPH/openmalaria/wiki#team) leads to

https://www.swisstph.ch/en/about-us/departments/epidemiology-and-public-health-eph/health-systems-research-and-dynamical-modelling/dynamical-modelling.html, which probably don't exists anymore.

**Comment by ManuelaRunge** [comment]
Thanks,

updated link from: (https://www.swisstph.ch/en/about-us/departments/epidemiology-and-public-health-eph/health-systems-research-and-dynamical-modelling/dynamical-modelling.html)  to: (https://www.swisstph.ch/en/about/eph/infectious-disease-modelling/)
