### ISSUE TITLE
Building OpenMalaria for MacOS

### ISSUE THREAD

**Issue by ggrrll** [SwissTPH/openmalaria#210]
Hi, 

I am on Mac OS 10.13.6 -- kernel: Darwin 17.7.0
After pasting the folder locally and running `./openMalaria --version`,  I get 

```
dyld: Library not loaded: /usr/local/opt/gsl/lib/libgsl.19.dylib
  Referenced from: /Users/lazzari/Documents/venezuela_outbreaks/openMalaria-osx/./openMalaria
  Reason: image not found
Abort trap: 6
```

  I eliminated Xcode cache [as suggested here](https://stackoverflow.com/questions/27116371/dyld-library-not-loaded-reason-no-suitable-image-found/43466989#43466989) but didn't help...
any idea ?

Thanks

**Comment by ThomasASmith** [comment]
As far as we are aware you are the only one trying to run this on a Mac at the moment.
The most recent versions have not been built for the Mac.
Which version are you trying to use?

**Comment by ggrrll** [comment]
hi, sorry for the late reply -- our proj. on malaria is currently on pause and I don't know if/when we are gonna use openmalaria -- 

anyways, this is the output

<img width="1412" alt="screenshot 2018-12-13 at 09 54 58" src="https://user-images.githubusercontent.com/15370425/49926989-31a57080-febd-11e8-9448-2fe8e2dc762f.png">

thanks for the support

**Comment by ThomasASmith** [comment]
pasting an email response from @dhardy  :we are attempting to have
automated builds for all desktop platforms (including OSX). As you can
see here, the build succeeds, though the upload currently fails:

https://travis-ci.org/SwissTPH/openmalaria/jobs/468608072

The build uses this script to install dependencies:

https://github.com/SwissTPH/openmalaria/blob/master/util/install-dep-osx.sh

**Comment by ggrrll** [comment]
ok thanks -- I will give it a try in case

**Comment by dhardy** [comment]
The automated builds now function correctly; you should be able to download a working binary from there, for example:

https://github.com/SwissTPH/openmalaria/releases/tag/schema-39.1.4

If these binaries don't work for you, please open a new issue.

**Comment by ggrrll** [comment]
thanks! I will check it out
