### ISSUE TITLE
Intervention deployment triggers

### ISSUE THREAD

**Issue by GoogleCodeExporter** [SwissTPH/openmalaria#22]
```
Be able to simulate, for example, when a malarial case occurs in a 
low-transmission scenario and more cases are actively looked for.

That is, a malarial fever triggers a mass screen-and-treat intervention.
```

Original issue reported on code.google.com by `diggory....@gmail.com` on 30 Jun 2010 at 12:20

**Comment by dhardy** [comment]
@ThomasASmith what would a concrete use-case be? Who would use this?

**Comment by ThomasASmith** [comment]
This is needed for simulating surveillance response systems: when a sick person arrives to be treated it triggers some kind of community response (e.g. test and treat, or distributing nets, or spraying houses.

**Comment by dhardy** [comment]
@ThomasASmith sounds like a few more things need to be discussed. Presumably there's some cool-down time or something to not repeat the response for every case. And if response should be restricted to "the community" we need to discuss how to apply that to OM.

**Comment by ThomasASmith** [comment]
We can discuss when you are here.
Tom

On 07.11.2015 19:16, Diggory Hardy wrote:
>
> @ThomasASmith <https://github.com/ThomasASmith> sounds like a few more 
> things need to be discussed. Presumably there's some cool-down time or 
> something to not repeat the response for every case. And if response 
> should be restricted to "the community" we need to discuss how to 
> apply that to OM.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/SwissTPH/openmalaria/issues/22#issuecomment-154732965>.
>


-- 
Thomas Smith
Swiss Tropical & Public Health Institute
Department of Epidemiology & Public Health
Socinstrasse 57
P.O . Box
CH-4002 Basel
Switzerland
Tel  +41 61 284 8273 Fax +41 61 284 8101
email: Thomas-A.Smith@unibas.ch
http://www.swisstph.ch/about-us/departments/epidemiology-and-public-health-eph/health-systems-research-and-dynamical-modelling.html

**Comment by ThomasASmith** [comment]
We settled on the solution that:
- we agreed that the functionality needed is that anything recorded in a surveys should be able to trigger deployments (quantities that are age-specific must be added over the whole population).
- cohort/age specific triggers will not be supported  
- The conditions will refer to the previous survey (same or earlier time point).
- delays in deployment after the triggering condition is met are addressed by adjusting the interval between the triggering surveys.

Diggory will propose what the XML should look like.

**Comment by dhardy** [comment]
Milestones:

- [ ] non-reporting surveys
- [ ] conditions of the form "measured value is within specified range" which are set/unset by a survey
- [ ] repeating intervention deployments
- [ ] deployments active or not based on a configured condition

**Comment by dhardy** [comment]
Done.

**Comment by dhardy** [comment]
Here is [an example scenario](https://github.com/SwissTPH/openmalaria/blob/986fad17b893a21833e1d248c2a390bcc3ee0ec1/test/scenarioTriggeredMSAT.xml) and [the generated documentation](https://github.com/SwissTPH/openmalaria/wiki/GeneratedSchema35ADoc#elt-condition)

**Comment by dhardy** [comment]
I added some doc [here](https://github.com/SwissTPH/openmalaria/wiki/InterventionConditions) (see also [here](https://github.com/SwissTPH/openmalaria/wiki/Monitoring#unreported-surveys) and [here, under *conditions of deployment*](https://github.com/SwissTPH/openmalaria/wiki/ModelInterventions#human-allocated-interventions)).
