### ISSUE TITLE
Including Michael White's P. vivax model

### ISSUE THREAD

**Issue by ThomasASmith** [SwissTPH/openmalaria#226]
The model is described at:

https://static-content.springer.com/esm/art%3A10.1038%2Fs41467-018-05860-8/MediaObjects/41467_2018_5860_MOESM1_ESM.pdf

and there is C++ code at:

https://github.com/MWhite-InstitutPasteur/Pvivax_IBM

This could be an alternative to the existing P. vivax model

**Comment by dhardy** [comment]
WIP; code currently at: https://github.com/dhardy/openmalaria-1/tree/vivax
