### ISSUE TITLE
Issue with drug conversion model

### ISSUE THREAD

**Issue by sharma-raman** [SwissTPH/openmalaria#233]
I have hit an issue when evoking the drug conversion model for Artemether-DHA.

Please find the link to a Gist for the corresponding XML input file:

https://gist.github.com/sharma-raman/cd87a7ebfc445b189d8be2e645ca9583

I am getting the following error message:
```
BoincWrapper: not using BOINC
^M[  0%]        Code error: calculateFactor: error epsilon is large: 0.102515 (integral is 13.4196)
Call stack, starting from /home/sharmar/Documents/src/openmalaria-master_v40_debug/model/PkPd/Drug/LSTMDrugConversion.cpp:156:
+0x39e  OM::PkPd::LSTMDrugConversion::calculateDrugFactor(OM::WithinHost::CommonInfection*, double) const
+0x43   OM::PkPd::LSTMModel::getDrugFactor(OM::WithinHost::CommonInfection*, double) const
+0x25a  OM::WithinHost::CommonWithinHost::update(int, std::vector<double, std::allocator<double> >&, double, double)
+0x144  OM::Host::Human::update(bool)
+0xb8   OM::Population::update1(OM::SimTime)
+0x29d  OM::Simulator::start(scnXml::Monitoring const&)
+0x188  main()
+0xe7   __libc_start_main()
+0x2a   _start()
This is likely an error in the C++ code. Please report!
OpenMalaria: No such file or directory
```
I defined two AR drugs (AR_50fold and AR_sens) with conversion to two separate DHA metabolite definitions but only used AR_sens in the health system. This was to test whether we can use the  drug conversion model with dropping in resistances at some point. 

I also tried to a simplified version with just AR_sens defined (remove all definitions associated with AR_50fold), to check if the multiple definitions of drug conversions confused things and I got the same type of error:
```
rm: cannot remove 'timer.txt': No such file or directory
rm: cannot remove 'output.txt': No such file or directory
BoincWrapper: not using BOINC
^M[  0%]        Code error: calculateFactor: error epsilon is large: 0.102515 (integral is 13.4196)
Call stack, starting from /home/sharmar/Documents/src/openmalaria-master_v40_debug/model/PkPd/Drug/LSTMDrugConversion.cpp:156:
+0x39e  OM::PkPd::LSTMDrugConversion::calculateDrugFactor(OM::WithinHost::CommonInfection*, double) const
+0x43   OM::PkPd::LSTMModel::getDrugFactor(OM::WithinHost::CommonInfection*, double) const
+0x25a  OM::WithinHost::CommonWithinHost::update(int, std::vector<double, std::allocator<double> >&, double, double)
+0x144  OM::Host::Human::update(bool)
+0xb8   OM::Population::update1(OM::SimTime)
+0x29d  OM::Simulator::start(scnXml::Monitoring const&)
+0x188  main()
+0xe7   __libc_start_main()
+0x2a   _start()
This is likely an error in the C++ code. Please report!
OpenMalaria: No such file or directory
```
You help with this issue would be very much appreciated.

**Comment by dhardy** [comment]
Raman, the error is that the numerical integration function [`gsl_integration_qag`](https://www.gnu.org/software/gsl/doc/html/integration.html?highlight=gsl_integration_qag#c.gsl_integration_qag) completed with the estimated error (0.102515) larger than the tolerance allowed (0.05). The requested absolute and relative tolerance is 0.01, with `key = 1`.

We could just try tweaking the parameters or could investigate why this function is hard to integrate.

**Comment by sharma-raman** [comment]
Diggory,

How about tweaking it to get to run (OM v40.1 beta), and then  examine the answer for validity; examining the reason for the integration error if required???

**Comment by sharma-raman** [comment]
Diggory,

How about tweaking it to get to run (OM v40.1 beta), and then  examine the answer for validity; examining the reason for the integration error if required???
