### ISSUE TITLE
Gaps in documentation

### ISSUE THREAD

**Issue by GoogleCodeExporter** [SwissTPH/openmalaria#33]
```
There are still gaps in the wiki documentation:

* non-malaria fever model
* model parameters: descriptions and sets of fit parameters

Probably there are more; please add to this ticket or better resolve.
```

Original issue reported on code.google.com by `diggory....@gmail.com` on 27 Jan 2011 at 1:04

**Comment by tph-thuering** [comment]
Doc:
Sub-populations
http://code.google.com/p/openmalaria/wiki/ModelIntervMisc#Cohort_selection
http://code.google.com/p/openmalaria/wiki/Monitoring?ts=1398355377&updated=Monitoring#From_version_32

**Comment by dhardy** [comment]
[Simulation phases are documented](https://github.com/SwissTPH/openmalaria/wiki/ModelTimeUpdates#simulation-phases)

**Comment by dhardy** [comment]
Cohort selection is documented: https://github.com/SwissTPH/openmalaria/wiki/SubPopulations

**Comment by dhardy** [comment]
There is some documentation of non-malaria fevers here: https://github.com/SwissTPH/openmalaria/wiki/ScenarioHealthSystem

**Comment by dhardy** [comment]
That leaves model parameters. These are documented in various papers within the AJTMH supplement and a few more recent models.
