### ISSUE TITLE
allow run.py script to execute in parallel

### ISSUE THREAD

**Issue by GoogleCodeExporter** [SwissTPH/openmalaria#42]
```
The test/run.py script is frequently used for testing. It could support -j2 
like make or just do things in parallel.
```

Original issue reported on code.google.com by `diggory....@gmail.com` on 27 Nov 2013 at 12:13

**Comment by tph-thuering** [comment]
created a test-script for multiprocessing:
https://gist.github.com/tph-thuering/bccbb603a92a716f8146

TODO: adapt this to run.py

**Comment by tph-thuering** [comment]
TODO:
    - Find a solution for proper output handling with more than 1 process
    - Handle SIGINT properly: Stop running processes and close worker pool when CTRL+C is pressed in terminal
