### ISSUE TITLE
GVI-usage + IRS-usage

### ISSUE THREAD

**Issue by tph-thuering** [SwissTPH/openmalaria#56]
ITN, IRS usage param, percentage of use, add this param to GVI

In addition, would it be an option to add <usage> as an optional parameter for the GVI description (or is it there already and we somehow missed it)?

**Comment by dhardy** [comment]
Diggory suggests this may be as simple as to copy the usage parameter from IRS to GVI (Tom)

**Comment by tph-thuering** [comment]
There is only an ITN usage element, not yet for IRS.

```
        <ITN>
          <usage value="0.8"/>
          ... sequence ...
         </ITN>
```
e.g. https://github.com/SwissTPH/openmalaria/blob/master/test/scenarioIRS30.xml#L68

**Comment by dhardy** [comment]
Uh, maybe the [IRS](https://github.com/vecnet/om_schema_docs/wiki/GeneratedSchema33Doc#elt-IRS) needs "usage" added too.

We went through the issues together.

**Comment by tph-thuering** [comment]
Done
