### ISSUE TITLE
Adjust documentation for new timestep inputs (XML)

### ISSUE THREAD

**Issue by tph-thuering** [SwissTPH/openmalaria#57]
Adjust documentation to represent the current state of code:

1.  check wiki has documentation on dates and timestep units
2.  update examples on wiki / snippets to use dates or units
3.  clarify what a timestep is:
    
    Dates should refer to a particular day at midday; a timestep is the update between two dates (midday to midday, either one day or five).

Additionally, is this implemented? :
2: automatically determine start of simulation
Simulation (intervention period) should start with first survey.
No interventions should be allowed before this date.

**Comment by dhardy** [comment]
Done, except the last bit: start is determined by `startDate` if using dates, otherwise as time 0.
