### ISSUE TITLE
Decision tree opt

### ISSUE THREAD

**Issue by tph-thuering** [SwissTPH/openmalaria#58]
CM decision trees could be optimised on loading by reordering.

See TODO here: https://github.com/SwissTPH/openmalaria/blob/master/model/Clinical/CMDecisionTree.cpp#L170

**Comment by dhardy** [comment]
Some notes:

CaseType: if there is a child decision with the same type, it is redundant.

Diagnostic: no optimisations.

Random: child decisions could be folded into the parent. The tree between these
points and other descendents of the child being optimised out must be
duplicated, except that the other descendents might be optimisible simultaneously.

Age: child descisions might be redundant; if not they could be folded into a
parent descision node with duplication (as for random).

[DTchanges.diff.txt](https://github.com/SwissTPH/openmalaria/files/97920/DTchanges.diff.txt)

**Comment by ThomasASmith** [comment]
to implement as part of a possible major rewrite
