### ISSUE TITLE
complete mosquito population dynamics model

### ISSUE THREAD

**Issue by tph-thuering** [SwissTPH/openmalaria#61]

**Comment by dhardy** [comment]
There is a functional simple mosquito population dynamics model. This may be sufficient. There are test scenarios: test/scenarioSimpleMPD*

**Comment by tph-thuering** [comment]
For reference:
- https://github.com/SwissTPH/openmalaria/blob/master/test/scenarioSimpleMPDTest.xml
- https://github.com/SwissTPH/openmalaria/blob/master/test/scenarioSimpleMPDLarviciding.xml
