### ISSUE TITLE
Add SSE2 Support

### ISSUE THREAD

**Issue by tph-thuering** [SwissTPH/openmalaria#62]
Add SSE2 Instructions for better performance.

Enable -msse2 -mfpmath=sse

see also: https://github.com/herumi/fmath

**Comment by dhardy** [comment]
I think we started enabling this (or at least SSE) on build systems for reproducibility. Shouldn't we set this in the CMake files now?

**Comment by tph-thuering** [comment]
added to branch `add-sse2-support#62`

ctest is now MUCH faster on my machine. 
__74__ s instead of 192 s.

@pemberto might be happy now.

**Comment by pemberto** [comment]
I'm always happy, @tph-thuering !

That is a formidable speed up. If you can incorporate this into a sciCORE build for v33, I will test it next week.

**Comment by tph-thuering** [comment]
Merged this now into develop. Scheduled to be in schema-34.1 https://github.com/SwissTPH/openmalaria/milestones/Schema-34.1
