### ISSUE TITLE
Update documentation about SwissTPH/openmalaria.tools .

### ISSUE THREAD

**Issue by tph-thuering** [SwissTPH/openmalaria#64]
These tools might be helpful for users and are worth to be documented in the wiki properly:

https://github.com/SwissTPH/openmalaria.tools

Document these scripts in the wiki:
* [ ] generateDoc.py
* [x] plotResult.py
* [ ] readOutput.py
* [ ] reformat_xmls.py
* [ ] translateXML.py

**Comment by tph-thuering** [comment]
Also update https://github.com/SwissTPH/openmalaria/wiki/XmlUpdateScenario

**Comment by tph-thuering** [comment]
@tph-thuering: TODO Also update https://github.com/SwissTPH/openmalaria/wiki/XmlUpdateScenario

**Comment by dhardy** [comment]
[Several of these are documented already](https://github.com/SwissTPH/openmalaria/wiki/UtilsRunScripts)

**Comment by dhardy** [comment]
Done: https://github.com/SwissTPH/openmalaria.tools/blob/master/README.md
