### ISSUE TITLE
Add linux build deployment hook

### ISSUE THREAD

**Issue by tph-thuering** [SwissTPH/openmalaria#66]
add deployment hook for every new release (or evaluate if this is possible with Travis CI)

successor of #50 

Purpose:

Every time the master branch is updated, CI should verify if the build and tests succeed and upload a new release with updated version information for the last version to [github-releases](https://github.com/SwissTPH/openmalaria/releases).

**Comment by sgtbigman** [comment]
Link of possible interest: [GitHub Releases Uploading](http://docs.travis-ci.com/user/deployment/releases/)

**Comment by tph-thuering** [comment]
Added deployment entry for travis. 
Needs testing:
------------------

As soon as there is a new Release, just do a 
```
$ git tag schema-XX.Y
$ git push --tags 
```

This should create a new linux build release under [releases](https://github.com/SwissTPH/openmalaria/releases)

**Comment by tph-thuering** [comment]
Implemented for branch CERN-schema-33
TODO: Port these changes to master

**Comment by tph-thuering** [comment]
TODO: travis-ci legacy upgrade: http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade

**Comment by tph-thuering** [comment]
Done
