### ISSUE TITLE
Easier-to-use output format

### ISSUE THREAD

**Issue by tph-thuering** [SwissTPH/openmalaria#69]
## Easier-to-use output format

Currently, all outputs are in a backwards-compatible format, which has the
following issues:
1.  Age-group, cohort identifier, vector species (never concurrent with
   age-group) and parasite genotype are all coerced into the same column.
   Having two extra columns would make parsing easier.
2.  The times of surveys are not given in the output and require analysing the
   XML documents or using the --print-survey-times option (added after the 33
   release).
3.  Similarly, age-groups, cohorts, vector species, genotypes and measures are
   all given via suome type of numeric index whose meaning is not obvious
   without examining the XML. It is not clear whether this should be fixed.

If a new output format is introduced, it **must** be optional via some type of
switch so that old code like analysis of fitting runs does not need updating.

Possible changes:
-   Replace survey number with a date or time-step
-   Add in two new "key" columns (besides age-group); make the meaning of all
  three columns depend on the measure (e.g. (age-group, genotype, cohort) or
  (vector-species, genotype)
-   Re-order columns
-   Change the format of columns from plain numbers to strings; e.g. age-groups
  could become "0d-30d", "5y-10y"; cohort membership could be binary "1101"
  or text-based "ABD". Measures could indicate _what_ is measured and
  _categorisation_, e.g. "30-AG" for measure 30 by age and genotype.
  **Major down-side:** analysis tools have to parse these which makes them
  much more complicated.
-   Keep plain numerical keys in columns but add a key (list of meanings) in a
  separate file which details what all numbers mean. Note that this key file
  could be generated only in the presence of a specific command-line option
  such that it only needs to be generated once for each experiment (assuming
  all age-groups, measures, etc. are constant across the experiment, which is
  usually the case).

**Comment by Baguage** [comment]
Just as feedback from VecNet developers: existing survey output format is darn difficult to process. Original xml input file is required to obtain survey timestamps and age groups. Also, channel 21/allCauseIMR needs special handling in output processor:
 - it can produce NaN value on timestep 0
 - only one value with survey number 0 (I believe) is saved to output file
We have separate python library to handle this, but I'm still not 100% sure we cover all possible cases.

Also, as a suggestion: it would be helpful for VecNet web interface if OpenMalaria can (optionally) produce output in new and old formats simultaneously. That way users can download results in format that suits their needs.

**Comment by ThomasASmith** [comment]
All great ideas for a major code rewrite.
