### ISSUE TITLE
Improve Monitoring code

### ISSUE THREAD

**Issue by tph-thuering** [SwissTPH/openmalaria#70]
Monitoring code still needs some improvements

The following should be fixed:

1. the REPORT_ONLY_AT_RISK option should be part of the monitoring system, not a general option
2. output file is not very easy to use and quite restrictive
3. documentation of new measures and ways of modifying them is poor to non-existant

**Comment by dhardy** [comment]
Reminder to self: check whether this is done

**Comment by dhardy** [comment]
I've spent a while improving the monitoring *code*. Worked out how to implement `REPORT_ONLY_AT_RISK` in a better way (allowing both "only at risk" and "all cases" outputs in the same simulation), but it's a lot of extra complexity for a rarely used feature, so it's probably better just to disable it.

@ThomasASmith any comments?

**Comment by ThomasASmith** [comment]
I agree that this is not critical.  So long as we can separately extract these outputs it is not important to be able to do this in the same simulation.

**Comment by dhardy** [comment]
Okay, `REPORT_ONLY_AT_RISK` has been replaced by the survey option `<SurveyOptions onlyNewEpisode="true">`. Documentation:

          If set, some statistics exclude humans who have been treated in the
          recent past (precisely, when the time of last treatment was before
          the current step and no more than health-system-memory days/steps
          ago).
          
          This is a rough replacement for the REPORT_ONLY_AT_RISK option,
          with one difference: the maximum age of treatment for
          REPORT_ONLY_AT_RISK was fixed at 20 days.
          
          Affected measures include (as of version 35):
          nHost (0),
          nInfect(1),
          nExpectd (2),
          nPatent (3),
          sumLogPyrogenThres (4),
          sumlogDens (5),
          totalInfs (6),
          totalPatentInf (8),
          sumPyrogenThresh (10),
          nSubPopRemovalFirstEvent (62),
          sumAge (68),
          nInfectByGenotype (69),
          nPatentByGenotype (70),
          logDensByGenotype (71),
          nHostDrugConcNonZero (72),
          sumLogDrugConcNonZero (73).

@ThomasASmith @rossaman I'm pretty sure these are the only outputs affected, and this is exactly the same as the old option except no longer being fixed at 20 days.

**Comment by dhardy** [comment]
Made a new issue for point 2: #159

**Comment by dhardy** [comment]
Added some doc. regarding third point: https://github.com/SwissTPH/openmalaria/wiki/Monitoring#categorisation
