### ISSUE TITLE
More flexible output measures

### ISSUE THREAD

**Issue by tph-thuering** [SwissTPH/openmalaria#71]
More flexible output measures
-------------

These are old notes; something similar has been implemented but needs
documenting in the wiki/alternative location.

Configure output sets, each of which specifies:
a) to which humans it applies (age restrictions, not-at-risk, cohort)
b) age groups to report
c) reporting times
d) a list of reports, each of which may specifies:
d.i) the thing to report (e.g. diagnostic)
d.ii) optional restrictions (e.g. only RDTs and only from mass deployment)
d.iii) code used in output (like the current Clinical_RDTs = 39)
e) the output file name/number and format

Note on e): currently output file name is specified via command-line option;
specifying in XML will conflict. May also be a security issue.

**Comment by dhardy** [comment]
This was done (roughly)
