### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by tph-thuering** [SwissTPH/openmalaria#73]
Create a [docker](https://www.docker.com/whatisdocker/) container for latest openmalaria build.

UPDATE: [Dockerfile from Nic](https://registry.hub.docker.com/u/reednb/openmalaria/dockerfile/)

**Comment by Baguage** [comment]
I'm not familiar with Docker, but I believe we have created Vagrant file to create development enviroment in VirtualBox VM. I wonder if this can be converted into a Docker container.

**Comment by sgtbigman** [comment]
I started work on creating an automated build for openmalaria. The initial Dockerfile is utilized at this [link](https://registry.hub.docker.com/u/reednb/openmalaria/dockerfile/). The next step is figuring out what we want the docker container to do exactly.

Do we want to have users run openmalaria from within the container (Docker allows for shell access on containers), or do we want to allow users to run openmalaria from the container, but on local directories (i.e., ./openMalaria without being in the container's shell)? Note that one can also mount local directories to the container, which may be helpful.

I guess my question revolves more around, what is the target audience for this Docker container?

**Comment by tph-thuering** [comment]
1. We could use it for the travis build system http://docs.travis-ci.com/user/workers/container-based-infrastructure
1. We could use it to build to local directories with static linking (prerequisite: #74)
