### ISSUE TITLE
Improve static linking handling

### ISSUE THREAD

**Issue by tph-thuering** [SwissTPH/openmalaria#74]
1. Apply patch: https://gist.github.com/tph-thuering/bce2775ab61ccb0921ab
2. Try to build all libraries statically into openmalaria.

**Pro:**
- No need to install libraries and to ship separate files (e.g. xerces-c)
- easier deployment

**Contra:**
- Much bigger binary

Alternative: #73

**Comment by ThomasASmith** [comment]
Not a real problem at the moment according to @dhardy
