### ISSUE TITLE
Track build Test times

### ISSUE THREAD

**Issue by tph-thuering** [SwissTPH/openmalaria#76]
It might be a good idea to compare performance of Tests ( output of ctest ) to be aware of performance regressions.

Extracting outputs from travis builds:
e.g. https://travis-ci.org/SwissTPH/openmalaria/builds/62108421#L489
## TODO: 

Add a script, which pulls travis data and uploads build test times to a database. (or look for a cloud service, which does this)

**Comment by dhardy** [comment]
Are automated performance tests even feasible? What if the server is loaded with other work?

**Comment by tph-thuering** [comment]
@dhardy I guess you are right. If we want to do this, then we would need to do it on a separate build-machine. It can be done retroactively anyway, so maybe the effort to do it for every build is not feasible at this time.
