### ISSUE TITLE
Populate snippets library

### ISSUE THREAD

**Issue by dhardy** [SwissTPH/openmalaria#78]
This should involve analysing existing baseline XMLs and intervention arms, de-duplicating, adding documentation (perhaps involving authors) and organising.

**Comment by dhardy** [comment]
(Suggested by Tom, not me)

**Comment by tph-thuering** [comment]
@dhardy when? Yes, Tom suggested that, I think Nathalie from ND is working on that.

**Comment by dhardy** [comment]
On Saturday.
