### ISSUE TITLE
Add polyclonal inoculations

### ISSUE THREAD

**Issue by ThomasASmith** [SwissTPH/openmalaria#79]
OM needs the capacity to consider inoculations consisting of up to 2 parasite clones, where the number of clones inoculated is a function of the heterozygosity of the oocysts (assuming 1 oocyst contributing to each inoculum).  The heterozygosity should be an increasing function of EIR (not clear what the functional form should be).  Data for parameterising models of this can come from the studies of Babiker  and Paul (maybe there are also more recent papers on this). Anna Färnert (Karolinska) is currently planning a metaanalysis of studies of multiple infections that will help estimate the EIR-heterozygosity relationship.  This functionality will be important for modeling genetic recombination of resistance mutations, and would also facilitate fitting of the Molineaux model (on the assumption that the Molineaux within-host model represents the behaviour of a single clone).

**Comment by dhardy** [comment]
Could you translate this into less jargon-heavy language please?

**Comment by ian-hastings** [comment]
I am not convinced this is necessary at this point: most models of antimalarial drug resistance  have assumed each bite inoculates only a single clone.Genetic diversity in human blood arises from repeated bites each of which inoculates a single clone. The clones persist for a long time (unless treated!) so overlap in time to create genetic diversity in the patients blood. There is some field evidence that bites can inoculate more than one clone but the one bite=one clone assumption seems adequate at present

**Comment by dhardy** [comment]
Assigning to Tom to work out priority with Ian.

**Comment by ThomasASmith** [comment]
I now suspect that the reason for poor fit in fitting runs 3400 and 3401 is that the infection durations are too short (and hence dry season prevalence too low.  It follows that simulating polyclonal inoculations may not improve the fit of the models, so it would be a complication that we do not need at this stage, so I am leaving it as low priority.
