### ISSUE TITLE
Integrate cpp-coverall / gcov

### ISSUE THREAD

**Issue by tph-thuering** [SwissTPH/openmalaria#82]
Subtask of #55 

Allows (probably easier) improvement of testing and performance.

http://gcc.gnu.org/onlinedocs/gcc/Gcov.html

**Comment by tph-thuering** [comment]
Check binary with 
```
nm openMalaria | grep "gcov"
```
if it contains gcov

**Comment by tph-thuering** [comment]
Integration of cpp-coverall is not yet done.

**Comment by tph-thuering** [comment]
work can be done on branch 'coveralls' https://github.com/SwissTPH/openmalaria/tree/coveralls

**Comment by dhardy** [comment]
I don't believe "full coverage" testing is particularly useful in the case of OpenMalaria.
