### ISSUE TITLE
Update doxygen code documentation

### ISSUE THREAD

**Issue by tph-thuering** [SwissTPH/openmalaria#84]
Currently doxygen code documentation is outdated:

https://github.com/SwissTPH/openmalaria/wiki/Code#doxygen-documentation

Fix this.

1. Automate doxygen code generation (Probably with travis?)

**Comment by dhardy** [comment]
@tph-thuering @ThomasASmith does anyone use or want the doxygen doc? As a programmer I prefer the code and for non-programmers I don't think it's appropriate.

**Comment by tph-thuering** [comment]
@dhardy I generated it locally and don't think anybody else than programmers would use an online-version. Programmers would probably be able to generate it themselves anyway. Automation would be nice, but at this point not so useful.

**Comment by tph-thuering** [comment]
Done. Removed page and references in the wiki.
