### ISSUE TITLE
Insecticide resistance

### ISSUE THREAD

**Issue by tph-thuering** [SwissTPH/openmalaria#85]
**competition between larval stages:** resistant mosquitoes should be able to achieve dominance over sensitive mosquitoes

@nakul7: could you comment on that? Probably add some links to documentation on how to implement this.

**Comment by nakul7** [comment]
@tph-thuering Toby - We have a set of equations for this as part of a publication in presentation. We can go through this together. The best solution would be to add the publication to the documentation - but we can only do this after it is accepted for publication.

**Comment by dhardy** [comment]
Depends on #41 .

**Comment by dhardy** [comment]
Reduced priority to match #41.

**Comment by ThomasASmith** [comment]
In general suggest work on this should be as a stand-alone ento model, not as part of OpenMalaria (see #41 also)
