### ISSUE TITLE
Vector traps

### ISSUE THREAD

**Issue by tph-thuering** [SwissTPH/openmalaria#86]
excerpt from email conversation between @dhardy and @nakul7:
# summary of effects we need:

**multiplier on prob survival when biting, decaying to 1 (we don't have to worry about pre/post feeding)**
_I assume that we can use the same options for delay that we currently
offer for other interventions: for traps, there will likely be no decay
because the assumption will be that the traps are regularly maintained.
And for all the interventions that I can think of, we won't need to
worry about the distinction between post and pre-feeding. (Even if some
insecticides kill before feeding, that should make no difference to
malaria dynamics)._

**multiplier on availability, decaying to 1 (i.e. the deterrent)**
_Yes, that works. We most likely won't need this but it is better to
include it now in case there is an intervention that needs it._

**change availability permanently/until changed again**
_Yes, this should allow us to add traps or change the coverage of
insecticide treated cattle._

**Does setting the availability of traps give sufficient control of how many mosquitoes they attract? Is it easy enough to convert, say, a percentage of mosquitoes caught, to an availability (if we need this way of parameterising)? This is I suppose your point about coverage levels...**
_One option would be to expose the user to parameters that are simpler
than what the model uses and do the conversion ourselves. For example,
for odour-baited traps, we could ask the user to input_
- the _relative attractiveness of traps to humans_ (which can be measured
  in the lab in odour tunnels as the ratio of mosquitoes that fly to traps
  that fly to one human)
- the _number of traps to humans_,
- the _decay curve and duration of effectiveness_, with the assumption that the mortality rate is 100%
  For insecticide treated livestock, the inputs would be,
- the _proportion of animals covered by insecticide_ (we can assume that
  this is equivalent to the proportional availability of treated non-human
  hosts - but if we want to get more complicated we can divide this into
  different kinds of animals like cows and goats)
  b) the additional mortality of the insecticide
  c) the decay curve and duration.

_We will need to decide whether we want to provide these as two different
interventions where we do the conversion of parameters within
openmalaria or offer them as generic interventions (in the same style as
the other vector control interventions) and ask the users to work
through the conversion of parameters. My preference would be to offer
the generic intervention and leave the conversion to a pre-processor
like the VecNet OpenMalaria interface_

**Comment by nakul7** [comment]
@tph-thuering Let's work through this together - the main changes to the code needed are to add the capability of including new generic interventions and modelling their effects on non-human hosts.

**Comment by dhardy** [comment]
@nakul7 @ThomasASmith set priority?

**Comment by ThomasASmith** [comment]
I propose to leave this as medium priority: we should discuss how important it is to add additional functionality- would adding a technically more satisfactory way of modeling vector traps lead to models that are more complicated than we need?  We can investigate many issues with stand-alone models or approximations.

**Comment by dhardy** [comment]
@tph-thuering shall I take this or are you in the middle of it?

**Comment by tph-thuering** [comment]
@dhardy take it.

**Comment by dhardy** [comment]
@nakul7 will provide test cases.

**Comment by ThomasASmith** [comment]
Tobias Homan, Nakul, Olivier, & Tom have just agreed this is now a top priority for new functionality.

1. This should be in the form of a generic intervention that can change the parameters (with decay) of non-human hosts in the course of the intervention (traps are parameterised as non-human Hosts). 

This will also require:
2.  Each type of non-human host should be assigned the ('ratioToHumans') of how many such hosts exist per capita human population (this is implicitly currently set at 1) in addition to the availability (which is relative to other non-human hosts).  For backwards compatibility if no ratio is given it defaults to 1. In calculating the availability of non-human hosts, a ratio of 1 should always be used (not the ratio that is entered in the XML).

**Comment by nakul7** [comment]
Diggory and Nakul just agreed that the simplest solution is to simulate vector traps and other non-human host interventions (such as spraying cattle with insecticide or treating them with avermectin) as two separate interventions.

Vector traps should be specified by the time of deployment, the number of traps, the relative availability to an average adult human, and the survival before biting (P_B_i).  The traps should then be included as an additional non-human host that are incapable of transmitting malaria, with alpha_i the product of the relative availability to an adult human and the availability of an adult human, P_B_i as specified above and the other survival terms (P_C_i and P_D_i set to  1. It is likely that P_B_i will always be set to 0 but for generality we may as well allow this to be user defined. 

The traps should then also allow a general decay function - this is likely to be a constant for P_B_i; a constant or a step function for the number of traps; but it may have any distribution for the availability. If all parameters need to have the same decay curve, then we should strongly recommend that only a constant or a step function is used for the decay.

Other interventions should be modelled in a similar mannner to the generic vector intervention - with the same intervention parameters - simply targeted at non-human hosts. The only additional parameter should be the name of the non-human host that the intervention targets (for each mosquito species). We can leave propActive in for generalisibility but it is likely this will always be set to 1.

Note that sugar baits are already modelled as an intervention that increases the death rate of host-seeking mosquitoes. Until (if) we include a model for sugar feeding, we should leave these traps as such.

**Comment by dhardy** [comment]
@nakul7 @obriet should redeployments of traps replace old ones (i.e. assume all old traps are removed)?

Separate decay functions for availability and killing factor are possible. I see no point separating survival biting/escaping/resting into multiple survival factors.

**Comment by obriet** [comment]
"Separate decay functions for availability and killing factor are possible. I see no point separating survival biting/escaping/resting into multiple survival factors." killing (1-P_B_i) should always be 100%. If it is not, OpenMalaria assumes mosquitoes get a bloodmeal from the traps. The decay is in the availability (attractiveness of the traps). I understand animal baited traps (e.g. cattle) are under "other interventions" in Nakul's message above, with a change to GVI. 
Now, to your first question, I need more information. Yes, normally if the bait in the trap is refreshed, the old bait is removed. Not sure how you would program that. I thought we could specify the max duration of a trap, and simply set that to just before redeployment (so that the old bait is not still active).

**Comment by dhardy** [comment]
@obriet I don't see a need to model traps as individual agents, so effectively there will be an availability (base human avail × factor × number traps) and a decay factor. The simplest way to redeploy would be to reset the decay factor, and potentially update the other number (e.g. if number traps increases).

This may not work well if the number of traps is reduced and redeployed before complete decay, or if step-wise deployment is used (this would need a model).

**Comment by dhardy** [comment]
@nakul7 @obriet please check this potential schema for "baited traps":
https://github.com/SwissTPH/openmalaria/wiki/GeneratedVectorTrapsDoc#elt-anopheles

**Comment by dhardy** [comment]
[Implemented](https://github.com/SwissTPH/openmalaria/commit/6daed203cf080e8fb64268a521872f8d1354ad8f)

Now it needs some testing. Any ideas?

**Comment by ThomasASmith** [comment]
We (NC/TS) have been discussing tests based on simulating Rusinga

**Comment by ThomasASmith** [comment]
@nakul7 Is this the functionality that Adrian used for his pull simulations?
