### ISSUE TITLE
Get rid of .net dependency for Windows builds?

### ISSUE THREAD

**Issue by tph-thuering** [SwissTPH/openmalaria#90]
@dhardy  @ThomasASmith asked if we could get rid of the .net dependencies, as boinc builds do not need .net, when OM_STATICALLY_LINK is set for builds (or WITHOUT_BOINC is unset).

Question: Is this achievable easily?
I still have to do Windows builds for schema-34, so maybe this would make #54 easier to setup.

I see that .net is installed on many clients anyway, but if the cost of getting rid of the .net dependency is low, this would be great.

Update: Dependency #91

**Comment by tph-thuering** [comment]
Reference: https://github.com/SwissTPH/openmalaria/wiki/WindowsBuildOpenMalaria#compiling-without-a-net-dependency-and-with-xerces-statically-linked

**Comment by dhardy** [comment]
@tph-thuering Can you send me an email when you want to ask something please? I don't always check github notifications.

We used to avoid this dependency, and I think the 32-bit build image should do this (if it hasn't been reconfigured). There's a `USE_LIBCMT` option (something like that). Trouble is, you have to recompile all your libraries... and usually I still get xerces linker errors. I think Tarantino got around this sometimes by tweaking the compiler or linker command lines directly (not fixing the build system), but either way it's usually a case of torture by linker errors. Frankly I gave up.
