### ISSUE TITLE
Add XERCES_STATIC_LIBRARY to OpenMalaria compile targets.

### ISSUE THREAD

**Issue by tph-thuering** [SwissTPH/openmalaria#91]
See TODO part of: https://github.com/SwissTPH/openmalaria/wiki/WindowsBuildOpenMalaria#compiling-without-a-net-dependency-and-with-xerces-statically-linked

**Comment by tph-thuering** [comment]
This relates to #74

**Comment by ThomasASmith** [comment]
Linked to issue #90
