### ISSUE TITLE
Document schema-changes of version 33 in the wiki

### ISSUE THREAD

**Issue by tph-thuering** [SwissTPH/openmalaria#92]
Required:

- [x] MDA1D -> decisionTree, MDA -> treatSimple / treatPKPD
- [x] diagnostic changes for Screen intervention and CM decisions

Optional:

- [x] time units
- [x] dates
- [x] detectionLimit → diagnostic
- [ ] neonatal diagnostic
- [x] parasiteGenetics
- [x] monitoring

Output:
- [ ] vector species name replaced with number
- [x] innoculationsPerAgeGroup changed (now + cohort set)

### Imported from #104

Documentation (mostly for next schema version):

- [x] MDA/MSAT intervention change
- [ ] CM5DayDT
- [ ] CFR option
- [x] diagnostics
- [ ]     Neonatal mortality diagnostic
- [x] times, dates

Genetics:
- [x]     XML
- [x]     mapping
- [x]     only trackable with vector model in dynamic mode
- [x]     initial frequencies used until the intervention period
- [x]     imported infections use initial frequencies

Molineaux model changes:
- [x]     blood volume is now determined by age (i.e. not always adult volume); assumptions:
    
    *   initial density (PRBC/μl) is constant across hosts
    *   extinction threshold in number of parasites (PRBC) is constant across hosts
- [x]     bug fix: sampling of initial per-infection parameters when not in pairwise mode

Tools:

- [ ] plotResults.py

**Comment by tph-thuering** [comment]
Changelog has been updated: https://github.com/SwissTPH/openmalaria/wiki/Changelog#schema-version-34-pre-release

**Comment by dhardy** [comment]
Added checkboxes; set those with existing documentation and wrote a little additional documenation.

**Comment by dhardy** [comment]
There isn't any documentation on the neonatal mortality model anyway, except the original publication (not editable) and the XML schema. Not sure if we want to bother with this?

Vector species: I guess we can add documentation if we need it.

@tph-thuering want to document plotResults usage? There's no existing doc in the wiki but a mention in a couple of images.

DecisionTree5Day: doesn't appear to be documented except in XML schema.

Not sure what the CFR (case fatality rate) option was...

**Comment by dhardy** [comment]
The plotResult documentation is actually issue #64.

**Comment by dhardy** [comment]
New issue for case management doc: #146.

**Comment by dhardy** [comment]
New issue for neonatal mortality stuff: #147.
