### ISSUE TITLE
New vector model option: force-vector-capacity

### ISSUE THREAD

**Issue by tph-thuering** [SwissTPH/openmalaria#93]
New vector model option: forget emergence rates and force Nv from the input data given.

**Comment by nakul7** [comment]
It's OK to force the emergence rate from input data but strange to force N_v because the model allows mosquitoes to die. How would this be resolved?

**Comment by dhardy** [comment]
So the death rates of mosquitoes in N_v don't match those in O_v/S_v? It might be possible to tweak those based on changes in N_v but it's probably not a very accurate model.

I think this originates as one of Olivier's ideas(?). What might a use-case be?

**Comment by ThomasASmith** [comment]
Looks like another proliferation of options that is not necessary.
