### ISSUE TITLE
new-EIR-inputs

### ISSUE THREAD

**Issue by tph-thuering** [SwissTPH/openmalaria#94]
New EIR inputs
==========

Vector and non-vector?

annual level & seasonality pattern

seasonality from: larval resources, emergence, densities of flying vectors
(N_v, S_v), EIR

XML done

**Comment by dhardy** [comment]
Does this differ from #93 ? Note that if larval resources or densities of flying vectors are used for seasonality they need to be offset (or emergence if the model starts from larval resources).

**Comment by dhardy** [comment]
Closing; if we seriously want new EIR inputs we should create a new ticket with details and priority.
