### ISSUE TITLE
gametocyte-models

### ISSUE THREAD

**Issue by tph-thuering** [SwissTPH/openmalaria#95]
Drug treatment for Gametocytes
Does the underlying model need review?

**Comment by dhardy** [comment]
The Gametocyte model? It was a simple model on a five-day time step and crudely adapted for the one-day time step, but I am not aware of any real reason it needs review.

Some drugs should in theory clear Gametocytes... possibly the elements of the lagged Gametocyte array could be multiplied by some drug survival factor (or maybe just set to zero).

**Comment by dhardy** [comment]
I don't believe there is a current need to consider Gametocyte treatment or review this model.
