### ISSUE TITLE
c-str-change

### ISSUE THREAD

**Issue by tph-thuering** [SwissTPH/openmalaria#98]
Use
```
        const char some_name[] = "abc"
```
not
```
        const char* some_name = "abc"
```
Reason: the latter is an assignable pointer, and reads require an extra redirection(?)

**Comment by tph-thuering** [comment]
@sgtbigman Hey Nic, if you want to help, this issue might be not too hard to do for you.

**Comment by sgtbigman** [comment]
@tph-thuering I'm not sure there would be much gain from doing this, and I've always seen the ```const char*``` variety used in other projects (seems to be best practice).

If there are any non-const char arrays though, I could see converting those to std::string at some point.

**Comment by tph-thuering** [comment]
Use std::string instead of c-strings..

**Comment by tph-thuering** [comment]
http://www.cs.bu.edu/teaching/cpp/string/array-vs-ptr/
